
project_id = "ehvzhnzqcbzuirovwjsr"

[functions.stripe-webhook]
verify_jwt = false

[functions.brevo-email-webhook]
verify_jwt = false

[functions.imap-fetch-emails]
verify_jwt = true

[functions.smtp-send-email]
verify_jwt = true

[functions.update-testimonials-file]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.increment-blog-view]
verify_jwt = false
