import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ro' | 'fr' | 'pl' | 'de';

interface LanguageContextType {
  currentLanguage: Language;
  setCurrentLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About Us',
    packages: 'Packages',
    howItWorks: 'How It Works',
    testimonials: 'Testimonials',
    contact: 'Contact',
    orderNow: 'Order Now',
    signIn: 'Sign In',
    user: 'User',
    accountSettings: 'Account Settings',
    signOut: 'Sign Out',
    
    // Common
    selectLanguage: 'Select language',
    selectOption: 'Select an option',
    selectYourPackage: 'Select Your Package',
    loadingPackages: 'Loading packages...',
    mostPopular: 'Most Popular',
    
    // Page Titles and Content
    howItWorksTitle: 'How It Works',
    howItWorksSubtitle: 'Follow these simple steps to get your personalized song',
    aboutTitle: 'About Us',
    aboutSubtitle: 'Creating Musical Memories',
    aboutDescription1: 'We are passionate musicians dedicated to transforming your stories into beautiful, personalized songs that capture the essence of your most precious moments.',
    aboutDescription2: 'With years of experience in music composition and production, our team understands the power of music to evoke emotions and create lasting memories.',
    testimonialsTitle: 'What Our Clients Say',
    testimonialsSubtitle: 'Real stories from satisfied customers who turned their memories into music',
    packagesSubtitle: 'Select the perfect music package that fits your needs and budget',
    
    // Step Process
    choosePackage: 'Choose Your Package',
    choosePackageDesc: 'Select from our range of personalized music packages',
    tellYourStory: 'Tell Your Story',
    tellYourStoryDesc: 'Share the details and emotions you want captured',
    weCreate: 'We Create',
    weCreateDesc: 'Our team composes your unique musical piece',
    deliverDelight: 'Deliver & Delight',
    deliverDelightDesc: 'Receive your personalized song and cherish forever',
    
    // Team
    ourTeam: 'Our Team',
    leadComposer: 'Lead Composer',
    leadVocalist: 'Lead Vocalist',
    soundEngineer: 'Sound Engineer',
    songsCreated: 'Songs Created',
    yearsExperience: 'Years Experience',
    clientSatisfaction: 'Client Satisfaction',
    
    // Testimonials
    testimonial1: 'Working with MusicGift was amazing. They understood our story perfectly and created something magical!',
    author1: 'Maria & Alex',
    location1: 'Bucharest, Romania',
    testimonial2: 'The personalized song for our anniversary was beyond our expectations. Pure perfection!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Romania',
    testimonial3: 'Our wedding song still gives us chills every time we hear it. Thank you for this beautiful gift!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Romania',
    
    // 404 Page
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'The page you are looking for does not exist',
    returnHome: 'Return Home',
    
    // Order Page
    placeOrder: 'Place Order',
    orderSubtitle: 'Let\'s create something magical together. Fill out the form below to get started.',
    orderSent: 'Order sent!',
    orderThankYou: 'Thank you for your order. We will contact you soon to confirm the details.',
    orderError: 'Error',
    orderErrorMessage: 'An error occurred while saving the order. Please try again.',
    
    // Order Form Navigation
    backToHome: 'Back to Home',
    progress: 'Progress',
    previous: 'PREVIOUS',
    continue: 'CONTINUE',
    completeOrder: 'COMPLETE ORDER',
    submitting: 'SUBMITTING...',
    of: 'of',
    
    // Order Form Validation
    completeRequiredFields: 'Please complete all required fields',
    completeRequiredFieldsDesc: 'Make sure to fill in all required information before proceeding.',
    orderSubmittedSuccess: 'Order submitted successfully!',
    orderSubmittedDesc: 'Thank you for your order. We\'ll contact you soon with next steps.',
    somethingWentWrong: 'Something went wrong',
    tryAgainSupport: 'Please try again or contact support if the problem persists.',
    
    // Step Titles
    stepPackage: 'Package',
    stepDetails: 'Details',
    stepStory: 'Story',
    stepPreferences: 'Preferences',
    stepContact: 'Contact',
    
    // Step Configuration
    generalDetails: 'General details',
    storyAndEmotionalDetails: 'Story and emotional details',
    musicalPreferences: 'Musical preferences',
    confirmation: 'Confirmation',
    
    // Package Details
    whatsIncluded: 'What\'s included:',
    professionalQuality: 'Professional quality guaranteed',
    professionalQualityGuaranteed: 'Professional Quality Guaranteed',
    tellUsAboutRecipient: 'Tell Us About the Recipient',
    helpUnderstand: 'Help us understand who this special song is for and what occasion we\'re celebrating.',
    
    // Order Summary
    orderSummary: 'Order Summary',
    package: 'Package',
    delivery: 'Delivery',
    selectedAddons: 'Selected Addons',
    total: 'Total',
    
    // Help Section
    needHelp: 'Need Help?',
    mondayToFriday: 'Mon-Fri: 9AM-6PM',
    
    // Testimonial Section
    testimonialQuote: '"Working with MusicGift was amazing. They understood our story perfectly and created something magical!"',
    testimonialAuthor: '— Radu & Elena',
    
    // Packages
    personalPackage: 'Personal Package',
    businessPackage: 'Business Package',
    premiumPackage: 'Premium Package',
    artistPackage: 'Artist Package',
    instrumentalPackage: 'Instrumental Package',
    remixPackage: 'Remix Package',
    giftPackage: 'Gift Package',
    
    // Package Descriptions
    personalPackageDesc: 'A song written with soul – just for you and your loved ones.',
    personalPackageTagline: 'Ideal for birthdays, weddings or special occasions – we transform your story into a unique and emotional musical gift.',
    businessPackageDesc: 'Professional commercial songs for brands and companies.',
    businessPackageTagline: 'Perfect for advertising campaigns, brand anthems, or corporate events.',
    premiumPackageDesc: 'Premium quality song with advanced production and distribution.',
    premiumPackageTagline: 'Professional distribution on all platforms with promotional support.',
    artistPackageDesc: 'Full artistic collaboration for aspiring musicians.',
    artistPackageTagline: 'Complete music production with professional video and marketing.',
    instrumentalPackageDesc: 'Custom instrumental music in your desired genre.',
    instrumentalPackageTagline: 'Perfect for content creators, podcasts, or background music.',
    remixPackageDesc: 'Professional remix of your existing song.',
    remixPackageTagline: 'Transform your song with modern production techniques.',
    giftPackageDesc: 'Personalized musical gift with beautiful presentation.',
    giftPackageTagline: 'The perfect surprise for your loved ones with elegant delivery.',
    
    // Languages
    romanian: 'Romanian',
    english: 'English',
    french: 'French',
    german: 'German',
    polish: 'Polish',
  },
  ro: {
    // Navigation
    home: 'Acasă',
    about: 'Despre Noi',
    packages: 'Pachete',
    howItWorks: 'Cum Funcționează',
    testimonials: 'Testimoniale',
    contact: 'Contact',
    orderNow: 'Comandă Acum',
    signIn: 'Conectează-te',
    user: 'Utilizator',
    accountSettings: 'Setări cont',
    signOut: 'Deconectează-te',
    
    // Common
    selectLanguage: 'Selectează limba',
    selectOption: 'Selectează o opțiune',
    selectYourPackage: 'Selectează Pachetul',
    loadingPackages: 'Se încarcă pachetele...',
    mostPopular: 'Cel Mai Popular',
    
    // Page Titles and Content
    howItWorksTitle: 'Cum Funcționează',
    howItWorksSubtitle: 'Urmează acești pași simpli pentru a-ți obține cântecul personalizat',
    aboutTitle: 'Despre Noi',
    aboutSubtitle: 'Creăm Amintiri Muzicale',
    aboutDescription1: 'Suntem muzicieni pasionați dedicați transformării poveștilor tale în cântece frumoase, personalizate, care surprind esența momentelor tale cele mai prețioase.',
    aboutDescription2: 'Cu ani de experiență în compoziție și producție muzicală, echipa noastră înțelege puterea muzicii de a evoca emotions și de a crea amintiri de durată.',
    testimonialsTitle: 'Ce Spun Clienții Noștri',
    testimonialsSubtitle: 'Povești reale de la clienți mulțumiți care și-au transformat amintirile în muzică',
    packagesSubtitle: 'Selectează pachetul muzical perfect care se potrivește nevoilor și bugetului tău',
    
    // Step Process
    choosePackage: 'Alege Pachetul',
    choosePackageDesc: 'Selectează din gama noastră de pachete muzicale personalizate',
    tellYourStory: 'Spune-ne Povestea',
    tellYourStoryDesc: 'Împărtășește detaliile și emoțiile pe care vrei să le surprindem',
    weCreate: 'Noi Creăm',
    weCreateDesc: 'Echipa noastră compune piesa ta muzicală unică',
    deliverDelight: 'Livrăm & Încântăm',
    deliverDelightDesc: 'Primește cântecul tău personalizat și păstrează-l pentru totdeauna',
    
    // Team
    ourTeam: 'Echipa Noastră',
    leadComposer: 'Compozitor Principal',
    leadVocalist: 'Vocalist Principal',
    soundEngineer: 'Inginer de Sunet',
    songsCreated: 'Cântece Create',
    yearsExperience: 'Ani de Experiență',
    clientSatisfaction: 'Satisfacția Clienților',
    
    // Testimonials
    testimonial1: 'Să lucrez cu MusicGift a fost minunat. Au înțeles perfect povestea noastră și au creat ceva magic!',
    author1: 'Maria & Alex',
    location1: 'București, România',
    testimonial2: 'Cântecul personalizat pentru aniversarea noastră a depășit așteptările. Perfecțiune pură!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, România',
    testimonial3: 'Cântecul de nuntă ne dă fiori de fiecare dată când îl auzim. Mulțumim pentru acest cadou frumos!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, România',
    
    // 404 Page
    pageNotFound: 'Pagină Negăsită',
    pageNotFoundDesc: 'Pagina pe care o cauți nu există',
    returnHome: 'Înapoi Acasă',
    
    // Order Page
    placeOrder: 'Plasează Comanda',
    orderSubtitle: 'Să creăm ceva magic împreună. Completează formularul de mai jos pentru a începe.',
    orderSent: 'Comandă trimisă!',
    orderThankYou: 'Mulțumim pentru comandă. Vă vom contacta în curând pentru confirmarea detaliilor.',
    orderError: 'Eroare',
    orderErrorMessage: 'A apărut o eroare la salvarea comenzii. Încercați din nou.',
    
    // Order Form Navigation
    backToHome: 'Înapoi Acasă',
    progress: 'Progres',
    previous: 'ANTERIOR',
    continue: 'CONTINUĂ',
    completeOrder: 'FINALIZEAZĂ COMANDA',
    submitting: 'SE TRIMITE...',
    of: 'din',
    
    // Order Form Validation
    completeRequiredFields: 'Te rugăm să completezi toate câmpurile obligatorii',
    completeRequiredFieldsDesc: 'Asigură-te că completezi toate informațiile necesare înainte de a continua.',
    orderSubmittedSuccess: 'Comanda a fost trimisă cu succes!',
    orderSubmittedDesc: 'Mulțumim pentru comandă. Te vom contacta în curând cu următorii pași.',
    somethingWentWrong: 'Ceva nu a mers bine',
    tryAgainSupport: 'Te rugăm să încerci din nou sau să contactezi suportul dacă problema persistă.',
    
    // Step Titles
    stepPackage: 'Pachet',
    stepDetails: 'Detalii',
    stepStory: 'Poveste',
    stepPreferences: 'Preferințe',
    stepContact: 'Contact',
    
    // Step Configuration
    generalDetails: 'Detalii generale',
    storyAndEmotionalDetails: 'Poveste și detalii emoționale',
    musicalPreferences: 'Preferințe muzicale',
    confirmation: 'Confirmare',
    
    // Package Details
    whatsIncluded: 'Ce include:',
    professionalQuality: 'Calitate profesională garantată',
    professionalQualityGuaranteed: 'Calitate Profesională Garantată',
    tellUsAboutRecipient: 'Spune-ne despre destinatar',
    helpUnderstand: 'Ajută-ne să înțelegem pentru cine este această melodie specială și ce ocazie sărbătorim.',
    
    // Order Summary
    orderSummary: 'Sumar Comandă',
    package: 'Pachet',
    delivery: 'Livrare',
    selectedAddons: 'Extra-uri Selectate',
    total: 'Total',
    
    // Help Section
    needHelp: 'Ai nevoie de ajutor?',
    mondayToFriday: 'Lun-Vin: 9:00-18:00',
    
    // Testimonial Section
    testimonialQuote: '"Să lucrez cu MusicGift a fost minunat. Au înțeles perfect povestea noastră și au creat ceva magic!"',
    testimonialAuthor: '— Radu & Elena',
    
    // Packages
    personalPackage: 'Pachet Personal',
    businessPackage: 'Pachet Business',
    premiumPackage: 'Pachet Premium',
    artistPackage: 'Pachet Artist',
    instrumentalPackage: 'Pachet Instrumental',
    remixPackage: 'Pachet Remix',
    giftPackage: 'Pachet Cadou',
    
    // Package Descriptions
    personalPackageDesc: 'Un cântec scris cu suflet – doar pentru tine și cei dragi.',
    personalPackageTagline: 'Ideal pentru aniversări, nunți sau ocazii speciale – transformăm povestea ta într-un cadou muzical unic și emoționant.',
    businessPackageDesc: 'Melodii comerciale profesionale pentru branduri și companii.',
    businessPackageTagline: 'Perfect pentru campanii publicitare, imnuri de brand sau evenimente corporative.',
    premiumPackageDesc: 'Melodie premium cu producție avansată și distribuție.',
    premiumPackageTagline: 'Distribuție profesională pe toate platformele cu suport promoțional.',
    artistPackageDesc: 'Colaborare artistică completă pentru muzicienii aspiranți.',
    artistPackageTagline: 'Producție muzicală completă cu videoclip profesional și marketing.',
    instrumentalPackageDesc: 'Muzică instrumentală personalizată în genul dorit.',
    instrumentalPackageTagline: 'Perfect pentru creatorii de conținut, podcasturi sau muzică de fundal.',
    remixPackageDesc: 'Remix profesional al piesei tale existente.',
    remixPackageTagline: 'Transformă-ți piesa cu tehnici moderne de producție.',
    giftPackageDesc: 'Cadou muzical personalizat cu prezentare frumoasă.',
    giftPackageTagline: 'Surpriza perfectă pentru cei dragi cu livrare elegantă.',
    
    // Languages
    romanian: 'Română',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    polish: 'Polski',
  },
  fr: {
    home: 'Accueil',
    about: 'À Propos',
    packages: 'Forfaits',
    howItWorks: 'Comment Ça Marche',
    testimonials: 'Témoignages',
    contact: 'Contact',
    orderNow: 'Commander',
    signIn: 'Se connecter',
    user: 'Utilisateur',
    accountSettings: 'Paramètres du compte',
    signOut: 'Se déconnecter',
    selectYourPackage: 'Sélectionnez Votre Forfait',
    loadingPackages: 'Chargement des forfaits...',
    mostPopular: 'Le Plus Populaire',
    howItWorksTitle: 'Comment Ça Marche',
    howItWorksSubtitle: 'Suivez ces étapes simples pour obtenir votre chanson personnalisée',
    aboutTitle: 'À Propos de Nous',
    aboutSubtitle: 'Créer des Souvenirs Musicaux',
    aboutDescription1: 'Nous sommes des musiciens passionnés dédiés à transformer vos histoires en belles chansons personnalisées qui capturent l\'essence de vos moments les plus précieux.',
    aboutDescription2: 'Avec des années d\'expérience en composition et production musicale, notre équipe comprend le pouvoir de la musique pour évoquer des émotions et créer des souvenirs durables.',
    testimonialsTitle: 'Ce Que Disent Nos Clients',
    testimonialsSubtitle: 'Vraies histoires de clients satisfaits qui ont transformé leurs souvenirs en musique',
    packagesSubtitle: 'Sélectionnez le forfait musical parfait qui correspond à vos besoins et budget',
    choosePackage: 'Choisissez Votre Forfait',
    choosePackageDesc: 'Sélectionnez parmi notre gamme de forfaits musicaux personnalisés',
    tellYourStory: 'Racontez Votre Histoire',
    tellYourStoryDesc: 'Partagez les détails et émotions que vous voulez capturer',
    weCreate: 'Nous Créons',
    weCreateDesc: 'Notre équipe compose votre pièce musicale unique',
    deliverDelight: 'Livrer & Enchanter',
    deliverDelightDesc: 'Recevez votre chanson personnalisée et chérissez pour toujours',
    ourTeam: 'Notre Équipe',
    leadComposer: 'Compositeur Principal',
    leadVocalist: 'Vocaliste Principal',
    soundEngineer: 'Ingénieur du Son',
    songsCreated: 'Chansons Créées',
    yearsExperience: 'Années d\'Expérience',
    clientSatisfaction: 'Satisfaction Client',
    testimonial1: 'Travailler avec MusicGift était incroyable. Ils ont parfaitement compris notre histoire et ont créé quelque chose de magique!',
    author1: 'Maria & Alex',
    location1: 'Bucarest, Roumanie',
    testimonial2: 'La chanson personnalisée pour notre anniversaire a dépassé nos attentes. Pure perfection!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Roumanie',
    testimonial3: 'Notre chanson de mariage nous donne encore des frissons à chaque fois que nous l\'entendons. Merci pour ce beau cadeau!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Roumanie',
    pageNotFound: 'Page Non Trouvée',
    pageNotFoundDesc: 'La page que vous recherchez n\'existe pas',
    returnHome: 'Retour à l\'Accueil',
    whatsIncluded: 'Ce qui est inclus:',
    placeOrder: 'Passer Commande',
    orderSubtitle: 'Créons quelque chose de magique ensemble. Remplissez le formulaire ci-dessous pour commencer.',
    orderSent: 'Commande envoyée!',
    orderThankYou: 'Merci pour votre commande. Nous vous contacterons bientôt pour confirmer les détails.',
    orderError: 'Erreur',
    orderErrorMessage: 'Une erreur s\'est produite lors de l\'enregistrement de la commande. Veuillez réessayer.',
    backToHome: 'Retour à l\'accueil',
    progress: 'Progrès',
    previous: 'PRÉCÉDENT',
    continue: 'CONTINUER',
    completeOrder: 'FINALISER LA COMMANDE',
    submitting: 'ENVOI EN COURS...',
    of: 'de',
    stepPackage: 'Forfait',
    stepDetails: 'Détails',
    stepStory: 'Histoire',
    stepPreferences: 'Préférences',
    stepContact: 'Contact',
    personalPackage: 'Forfait Personnel',
    businessPackage: 'Forfait Entreprise',
    premiumPackage: 'Forfait Premium',
    artistPackage: 'Forfait Artiste',
    instrumentalPackage: 'Forfait Instrumental',
    remixPackage: 'Forfait Remix',
    giftPackage: 'Forfait Cadeau',
    required: '*',
    completeRequiredFields: 'Veuillez remplir tous les champs obligatoires',
    completeRequiredFieldsDesc: 'Assurez-vous de remplir toutes les informations nécessaires avant de continuer.',
    orderSubmittedSuccess: 'Commande soumise avec succès!',
    orderSubmittedDesc: 'Merci pour votre commande. Nous vous contactons bientôt avec les prochaines étapes.',
    somethingWentWrong: 'Quelque chose s\'est mal passé',
    tryAgainSupport: 'Veuillez réessayer ou contacter le support si le problème persiste.',
    generalDetails: 'Détails généraux',
    storyAndEmotionalDetails: 'Histoire et détails émotionnels',
    musicalPreferences: 'Préférences musicales',
    confirmation: 'Confirmation',
    professionalQuality: 'Qualité professionnelle garantie',
    professionalQualityGuaranteed: 'Qualité Professionnelle Garantie',
    tellUsAboutRecipient: 'Parlez-nous du destinataire',
    helpUnderstand: 'Aidez-nous à comprendre pour qui est cette chanson spéciale et quelle occasion nous célébrons.',
    orderSummary: 'Résumé de Commande',
    package: 'Forfait',
    delivery: 'Livraison',
    selectedAddons: 'Options Sélectionnées',
    total: 'Total',
    needHelp: 'Besoin d\'aide?',
    mondayToFriday: 'Lun-Ven: 9h-18h',
    testimonialQuote: '"Travailler avec MusicGift était incroyable. Ils ont parfaitement compris notre histoire et ont créé quelque chose de magique!"',
    testimonialAuthor: '— Radu & Elena',
    personalPackageDesc: 'Une chanson écrite avec âme – juste pour vous et vos proches.',
    personalPackageTagline: 'Idéal pour les anniversaires, mariages ou occasions spéciales.',
    businessPackageDesc: 'Chansons commerciales professionnelles pour marques et entreprises.',
    businessPackageTagline: 'Parfait pour les campagnes publicitaires ou événements corporatifs.',
    premiumPackageDesc: 'Chanson premium avec production avancée et distribution.',
    premiumPackageTagline: 'Distribution professionnelle sur toutes les plateformes.',
    artistPackageDesc: 'Collaboration artistique complète pour musiciens aspirants.',
    artistPackageTagline: 'Production musicale complète avec vidéo et marketing professionnels.',
    instrumentalPackageDesc: 'Musique instrumentale personnalisée dans le genre désiré.',
    instrumentalPackageTagline: 'Parfait pour créateurs de contenu ou musique de fond.',
    remixPackageDesc: 'Remix professionnel de votre chanson existante.',
    remixPackageTagline: 'Transformez votre chanson avec des techniques modernes.',
    giftPackageDesc: 'Cadeau musical personnalisé avec belle présentation.',
    giftPackageTagline: 'La surprise parfaite avec livraison élégante.',
    romanian: 'Roumain',
    english: 'Anglais',
    french: 'Français',
    german: 'Allemand',
    polish: 'Polonais',
  },
  pl: {
    home: 'Strona Główna',
    about: 'O Nas',
    packages: 'Pakiety',
    howItWorks: 'Jak To Działa',
    testimonials: 'Opinie',
    contact: 'Kontakt',
    orderNow: 'Zamów Teraz',
    signIn: 'Zaloguj się',
    user: 'Użytkownik',
    accountSettings: 'Ustawienia konta',
    signOut: 'Wyloguj się',
    selectYourPackage: 'Wybierz Swój Pakiet',
    loadingPackages: 'Ładowanie pakietów...',
    mostPopular: 'Najpopularniejszy',
    howItWorksTitle: 'Jak To Działa',
    howItWorksSubtitle: 'Wykonaj te proste kroki, aby otrzymać swoją spersonalizowaną piosenkę',
    aboutTitle: 'O Nas',
    aboutSubtitle: 'Tworzymy Muzyczne Wspomnienia',
    aboutDescription1: 'Jesteśmy pasjonatami muzyki oddanymi przekształcaniu Twoich historii w piękne, spersonalizowane piosenki, które oddają istotę Twoich najcenniejszych chwil.',
    aboutDescription2: 'Z latami doświadczenia w kompozycji i produkcji muzycznej, nasz zespół rozumie moc muzyki w wywoływaniu emocji i tworzeniu trwałych wspomnień.',
    testimonialsTitle: 'Co Mówią Nasi Klienci',
    testimonialsSubtitle: 'Prawdziwe historie od zadowolonych klientów, którzy zamienili swoje wspomnienia w muzykę',
    packagesSubtitle: 'Wybierz idealny pakiet muzyczny, który pasuje do Twoich potrzeb i budżetu',
    choosePackage: 'Wybierz Swój Pakiet',
    choosePackageDesc: 'Wybierz z naszej gamy spersonalizowanych pakietów muzycznych',
    tellYourStory: 'Opowiedz Swoją Historię',
    tellYourStoryDesc: 'Podziel się szczegółami i emocjami, które chcesz uchwycić',
    weCreate: 'Tworzymy',
    weCreateDesc: 'Nasz zespół komponuje Twój unikalny utwór muzyczny',
    deliverDelight: 'Dostarczamy i Zachwycamy',
    deliverDelightDesc: 'Otrzymaj swoją spersonalizowaną piosenkę i ciesz się nią na zawsze',
    ourTeam: 'Nasz Zespół',
    leadComposer: 'Główny Kompozytor',
    leadVocalist: 'Główny Wokalista',
    soundEngineer: 'Inżynier Dźwięku',
    songsCreated: 'Utworzone Piosenki',
    yearsExperience: 'Lata Doświadczenia',
    clientSatisfaction: 'Zadowolenie Klientów',
    testimonial1: 'Praca z MusicGift była niesamowita. Doskonale zrozumieli naszą historię i stworzyli coś magicznego!',
    author1: 'Maria & Alex',
    location1: 'Bukareszt, Rumunia',
    testimonial2: 'Spersonalizowana piosenka na naszą rocznicę przewyższyła nasze oczekiwania. Czysta perfekcja!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Rumunia',
    testimonial3: 'Nasza piosenka ślubna wciąż daje nam dreszcze za każdym razem, gdy ją słyszymy. Dziękujemy za ten piękny prezent!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Rumunia',
    pageNotFound: 'Strona Nie Znaleziona',
    pageNotFoundDesc: 'Strona, której szukasz, nie istnieje',
    returnHome: 'Powrót do Domu',
    whatsIncluded: 'Co jest zawarte:',
    placeOrder: 'Złóż Zamówienie',
    orderSubtitle: 'Stwórzmy razem coś magicznego. Wypełnij formularz poniżej, aby rozpocząć.',
    orderSent: 'Zamówienie wysłane!',
    orderThankYou: 'Dziękujemy za zamówienie. Skontaktujemy się z Tobą wkrótce, aby potwierdzić szczegóły.',
    orderError: 'Błąd',
    orderErrorMessage: 'Wystąpił błąd podczas zapisywania zamówienia. Spróbuj ponownie.',
    backToHome: 'Powrót do domu',
    progress: 'Postęp',
    previous: 'POPRZEDNI',
    continue: 'KONTYNUUJ',
    completeOrder: 'ZAKOŃCZ ZAMÓWIENIE',
    submitting: 'WYSYŁANIE...',
    of: 'z',
    stepPackage: 'Pakiet',
    stepDetails: 'Szczegóły',
    stepStory: 'Historia',
    stepPreferences: 'Preferencje',
    stepContact: 'Kontakt',
    personalPackage: 'Pakiet Osobisty',
    businessPackage: 'Pakiet Biznesowy',
    premiumPackage: 'Pakiet Premium',
    artistPackage: 'Pakiet Artysty',
    instrumentalPackage: 'Pakiet Instrumentalny',
    remixPackage: 'Pakiet Remix',
    giftPackage: 'Pakiet Prezentowy',
    required: '*',
    completeRequiredFields: 'Proszę wypełnić wszystkie wymagane pola',
    completeRequiredFieldsDesc: 'Upewnij się, że wypełniłeś wszystkie niezbędne informacje przed kontynuowaniem.',
    orderSubmittedSuccess: 'Zamówienie zostało złożone pomyślnie!',
    orderSubmittedDesc: 'Dziękujemy za zamówienie. Skontaktujemy się z Tobą wkrótce z następnymi krokami.',
    somethingWentWrong: 'Coś poszło nie tak',
    tryAgainSupport: 'Spróbuj ponownie lub skontaktuj się z pomocą techniczną, jeśli problem będzie się powtarzał.',
    generalDetails: 'Szczegóły ogólne',
    storyAndEmotionalDetails: 'Historia i szczegóły emocjonalne',
    musicalPreferences: 'Preferencje muzyczne',
    confirmation: 'Potwierdzenie',
    professionalQuality: 'Gwarantowana jakość profesjonalna',
    professionalQualityGuaranteed: 'Gwarantowana Jakość Profesjonalna',
    tellUsAboutRecipient: 'Opowiedz nam o odbiorcy',
    helpUnderstand: 'Pomóż nam zrozumieć, dla kogo jest ta specjalna piosenka i jaką okazję świętujemy.',
    orderSummary: 'Podsumowanie Zamówienia',
    package: 'Pakiet',
    delivery: 'Dostawa',
    selectedAddons: 'Wybrane Dodatki',
    total: 'Razem',
    needHelp: 'Potrzebujesz pomocy?',
    mondayToFriday: 'Pon-Pt: 9:00-18:00',
    testimonialQuote: '"Praca z MusicGift była niesamowita. Doskonale zrozumieli naszą historię i stworzyli coś magicznego!"',
    testimonialAuthor: '— Radu & Elena',
    personalPackageDesc: 'Piosenka napisana z duszą – tylko dla Ciebie i Twoich bliskich.',
    personalPackageTagline: 'Idealna na urodziny, wesela lub specjalne okazje.',
    businessPackageDesc: 'Profesjonalne piosenki komercyjne dla marek i firm.',
    businessPackageTagline: 'Idealne do kampanii reklamowych lub wydarzeń korporacyjnych.',
    premiumPackageDesc: 'Piosenka premium z zaawansowaną produkcją i dystrybucją.',
    premiumPackageTagline: 'Profesjonalna dystrybucja na wszystkich platformach.',
    artistPackageDesc: 'Pełna współpraca artystyczna dla aspirujących muzyków.',
    artistPackageTagline: 'Kompletna produkcja muzyczna z profesjonalnym wideo i marketingiem.',
    instrumentalPackageDesc: 'Spersonalizowana muzyka instrumentalna w pożądanym gatunku.',
    instrumentalPackageTagline: 'Idealna dla twórców treści lub muzyki tła.',
    remixPackageDesc: 'Profesjonalny remix Twojej istniejącej piosenki.',
    remixPackageTagline: 'Przekształć swoją piosenkę nowoczesnymi technikami.',
    giftPackageDesc: 'Spersonalizowany prezent muzyczny z piękną prezentacją.',
    giftPackageTagline: 'Idealna niespodzianka z elegancką dostawą.',
    romanian: 'Rumuński',
    english: 'Angielski',
    french: 'Francuski',
    german: 'Niemiecki',
    polish: 'Polski',
  },
  de: {
    home: 'Startseite',
    about: 'Über Uns',
    packages: 'Pakete',
    howItWorks: 'Wie Es Funktioniert',
    testimonials: 'Bewertungen',
    contact: 'Kontakt',
    orderNow: 'Jetzt Bestellen',
    signIn: 'Anmelden',
    user: 'Benutzer',
    accountSettings: 'Kontoeinstellungen',
    signOut: 'Abmelden',
    selectYourPackage: 'Wählen Sie Ihr Paket',
    loadingPackages: 'Pakete werden geladen...',
    mostPopular: 'Beliebtestes',
    howItWorksTitle: 'Wie Es Funktioniert',
    howItWorksSubtitle: 'Folgen Sie diesen einfachen Schritten, um Ihr personalisiertes Lied zu erhalten',
    aboutTitle: 'Über Uns',
    aboutSubtitle: 'Musikalische Erinnerungen Schaffen',
    aboutDescription1: 'Wir sind leidenschaftliche Musiker, die sich der Verwandlung Ihrer Geschichten in schöne, personalisierte Lieder widmen, die die Essenz Ihrer kostbarsten Momente einfangen.',
    aboutDescription2: 'Mit jahrelanger Erfahrung in Musikkomposition und -produktion versteht unser Team die Kraft der Musik, Emotionen zu wecken und bleibende Erinnerungen zu schaffen.',
    testimonialsTitle: 'Was Unsere Kunden Sagen',
    testimonialsSubtitle: 'Echte Geschichten von zufriedenen Kunden, die ihre Erinnerungen in Musik verwandelt haben',
    packagesSubtitle: 'Wählen Sie das perfekte Musikpaket, das zu Ihren Bedürfnissen und Ihrem Budget passt',
    choosePackage: 'Wählen Sie Ihr Paket',
    choosePackageDesc: 'Wählen Sie aus unserem Sortiment an personalisierten Musikpaketen',
    tellYourStory: 'Erzählen Sie Ihre Geschichte',
    tellYourStoryDesc: 'Teilen Sie die Details und Emotionen mit, die Sie einfangen möchten',
    weCreate: 'Wir Erschaffen',
    weCreateDesc: 'Unser Team komponiert Ihr einzigartiges Musikstück',
    deliverDelight: 'Liefern & Begeistern',
    deliverDelightDesc: 'Erhalten Sie Ihr personalisiertes Lied und schätzen Sie es für immer',
    ourTeam: 'Unser Team',
    leadComposer: 'Hauptkomponist',
    leadVocalist: 'Hauptsänger',
    soundEngineer: 'Toningenieur',
    songsCreated: 'Erstellte Lieder',
    yearsExperience: 'Jahre Erfahrung',
    clientSatisfaction: 'Kundenzufriedenheit',
    testimonial1: 'Mit MusicGift zu arbeiten war erstaunlich. Sie haben unsere Geschichte perfekt verstanden und etwas Magisches geschaffen!',
    author1: 'Maria & Alex',
    location1: 'Bukarest, Rumänien',
    testimonial2: 'Das personalisierte Lied für unseren Jahrestag übertraf unsere Erwartungen. Pure Perfektion!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Rumänien',
    testimonial3: 'Unser Hochzeitslied gibt uns immer noch Gänsehaut, jedes Mal wenn wir es hören. Danke für dieses schöne Geschenk!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Rumänien',
    pageNotFound: 'Seite Nicht Gefunden',
    pageNotFoundDesc: 'Die Seite, die Sie suchen, existiert nicht',
    returnHome: 'Zurück zur Startseite',
    whatsIncluded: 'Was ist enthalten:',
    placeOrder: 'Bestellung Aufgeben',
    orderSubtitle: 'Lassen Sie uns gemeinsam etwas Magisches schaffen. Füllen Sie das untenstehende Formular aus, um zu beginnen.',
    orderSent: 'Bestellung gesendet!',
    orderThankYou: 'Vielen Dank für Ihre Bestellung. Wir werden Sie bald kontaktieren, um die Details zu bestätigen.',
    orderError: 'Fehler',
    orderErrorMessage: 'Beim Speichern der Bestellung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    backToHome: 'Zurück zur Startseite',
    progress: 'Fortschritt',
    previous: 'ZURÜCK',
    continue: 'WEITER',
    completeOrder: 'BESTELLUNG ABSCHLIESSEN',
    submitting: 'WIRD GESENDET...',
    of: 'von',
    stepPackage: 'Paket',
    stepDetails: 'Details',
    stepStory: 'Geschichte',
    stepPreferences: 'Präferenzen',
    stepContact: 'Kontakt',
    personalPackage: 'Persönliches Paket',
    businessPackage: 'Business Paket',
    premiumPackage: 'Premium Paket',
    artistPackage: 'Künstler Paket',
    instrumentalPackage: 'Instrumental Paket',
    remixPackage: 'Remix Paket',
    giftPackage: 'Geschenk Paket',
    required: '*',
    completeRequiredFields: 'Bitte füllen Sie alle Pflichtfelder aus',
    completeRequiredFieldsDesc: 'Stellen Sie sicher, dass Sie alle erforderlichen Informationen eingeben, bevor Sie fortfahren.',
    orderSubmittedSuccess: 'Bestellung erfolgreich übermittelt!',
    orderSubmittedDesc: 'Vielen Dank für Ihre Bestellung. Wir werden Sie bald mit den nächsten Schritten kontaktieren.',
    somethingWentWrong: 'Etwas ist schiefgelaufen',
    tryAgainSupport: 'Bitte versuchen Sie es erneut oder kontaktieren Sie den Support, wenn das Problem weiterhin besteht.',
    generalDetails: 'Allgemeine Details',
    storyAndEmotionalDetails: 'Geschichte und emotionale Details',
    musicalPreferences: 'Musikalische Präferenzen',
    confirmation: 'Bestätigung',
    professionalQuality: 'Professionelle Qualität garantiert',
    professionalQualityGuaranteed: 'Professionelle Qualität Garantiert',
    tellUsAboutRecipient: 'Erzählen Sie uns über den Empfänger',
    helpUnderstand: 'Helfen Sie uns zu verstehen, für wen dieses besondere Lied ist und welchen Anlass wir feiern.',
    orderSummary: 'Bestellübersicht',
    package: 'Paket',
    delivery: 'Lieferung',
    selectedAddons: 'Ausgewählte Extras',
    total: 'Gesamt',
    needHelp: 'Brauchen Sie Hilfe?',
    mondayToFriday: 'Mo-Fr: 9:00-18:00',
    testimonialQuote: '"Mit MusicGift zu arbeiten war erstaunlich. Sie haben unsere Geschichte perfekt verstanden und etwas Magisches geschaffen!"',
    testimonialAuthor: '— Radu & Elena',
    personalPackageDesc: 'Ein Lied mit Seele geschrieben – nur für Sie und Ihre Lieben.',
    personalPackageTagline: 'Ideal für Geburtstage, Hochzeiten oder besondere Anlässe.',
    businessPackageDesc: 'Professionelle kommerzielle Lieder für Marken und Unternehmen.',
    businessPackageTagline: 'Perfekt für Werbekampagnen oder Unternehmensveranstaltungen.',
    premiumPackageDesc: 'Premium-Lied mit fortschrittlicher Produktion und Vertrieb.',
    premiumPackageTagline: 'Professioneller Vertrieb auf allen Plattformen.',
    artistPackageDesc: 'Vollständige künstlerische Zusammenarbeit für aufstrebende Musiker.',
    artistPackageTagline: 'Komplette Musikproduktion mit professionellem Video und Marketing.',
    instrumentalPackageDesc: 'Maßgeschneiderte Instrumentalmusik im gewünschten Genre.',
    instrumentalPackageTagline: 'Perfekt für Content-Ersteller oder Hintergrundmusik.',
    remixPackageDesc: 'Professioneller Remix Ihres bestehenden Liedes.',
    remixPackageTagline: 'Verwandeln Sie Ihr Lied mit modernen Produktionstechniken.',
    giftPackageDesc: 'Personalisiertes Musikgeschenk mit schöner Präsentation.',
    giftPackageTagline: 'Die perfekte Überraschung mit eleganter Lieferung.',
    romanian: 'Rumänisch',
    english: 'Englisch',
    french: 'Französisch',
    german: 'Deutsch',
    polish: 'Polnisch',
  }
};

const languageNames = {
  en: 'EN',
  ro: 'RO',
  fr: 'FR',
  pl: 'PL',
  de: 'DE'
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('ro');

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languageNames };
