import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ro' | 'fr' | 'pl' | 'de';

interface LanguageContextType {
  currentLanguage: Language;
  setCurrentLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About Us',
    packages: 'Packages',
    howItWorks: 'How It Works',
    testimonials: 'Testimonials',
    contact: 'Contact',
    orderNow: 'Order Now',
    signIn: 'Sign In',
    user: 'User',
    accountSettings: 'Account Settings',
    signOut: 'Sign Out',
    
    // Order Page
    placeOrder: 'Place Order',
    orderSubtitle: 'Let\'s create something magical together. Fill out the form below to get started.',
    orderSent: 'Order sent!',
    orderThankYou: 'Thank you for your order. We will contact you soon to confirm the details.',
    orderError: 'Error',
    orderErrorMessage: 'An error occurred while saving the order. Please try again.',
    
    // Order Form Navigation
    backToHome: 'Back to Home',
    progress: 'Progress',
    previous: 'PREVIOUS',
    continue: 'CONTINUE',
    completeOrder: 'COMPLETE ORDER',
    submitting: 'SUBMITTING...',
    of: 'of',
    
    // Order Form Validation
    completeRequiredFields: 'Please complete all required fields',
    completeRequiredFieldsDesc: 'Make sure to fill in all required information before proceeding.',
    orderSubmittedSuccess: 'Order submitted successfully!',
    orderSubmittedDesc: 'Thank you for your order. We\'ll contact you soon with next steps.',
    somethingWentWrong: 'Something went wrong',
    tryAgainSupport: 'Please try again or contact support if the problem persists.',
    
    // Step Titles
    stepPackage: 'Package',
    stepDetails: 'Details',
    stepStory: 'Story',
    stepPreferences: 'Preferences',
    stepContact: 'Contact',
    
    // Step Configuration
    choosePackage: 'Choose package',
    generalDetails: 'General details',
    storyAndEmotionalDetails: 'Story and emotional details',
    musicalPreferences: 'Musical preferences',
    confirmation: 'Confirmation',
    
    // Package Details
    whatsIncluded: 'What\'s included:',
    professionalQuality: 'Professional quality guaranteed',
    professionalQualityGuaranteed: 'Professional Quality Guaranteed',
    tellUsAboutRecipient: 'Tell Us About the Recipient',
    helpUnderstand: 'Help us understand who this special song is for and what occasion we\'re celebrating.',
    
    // Order Summary
    orderSummary: 'Order Summary',
    package: 'Package',
    delivery: 'Delivery',
    selectedAddons: 'Selected Addons',
    total: 'Total',
    
    // Help Section
    needHelp: 'Need Help?',
    mondayToFriday: 'Mon-Fri: 9AM-6PM',
    
    // Testimonial Section
    testimonialQuote: '"Working with MusicGift was amazing. They understood our story perfectly and created something magical!"',
    testimonialAuthor: '— Radu & Elena',
    
    // Packages
    personalPackage: 'Personal Package',
    businessPackage: 'Business Package',
    premiumPackage: 'Premium Package',
    artistPackage: 'Artist Package',
    instrumentalPackage: 'Instrumental Package',
    remixPackage: 'Remix Package',
    giftPackage: 'Gift Package',
    
    // Package Descriptions
    personalPackageDesc: 'A song written with soul – just for you and your loved ones.',
    personalPackageTagline: 'Ideal for birthdays, weddings or special occasions – we transform your story into a unique and emotional musical gift.',
    businessPackageDesc: 'Professional commercial songs for brands and companies.',
    businessPackageTagline: 'Perfect for advertising campaigns, brand anthems, or corporate events.',
    premiumPackageDesc: 'Premium quality song with advanced production and distribution.',
    premiumPackageTagline: 'Professional distribution on all platforms with promotional support.',
    artistPackageDesc: 'Full artistic collaboration for aspiring musicians.',
    artistPackageTagline: 'Complete music production with professional video and marketing.',
    instrumentalPackageDesc: 'Custom instrumental music in your desired genre.',
    instrumentalPackageTagline: 'Perfect for content creators, podcasts, or background music.',
    remixPackageDesc: 'Professional remix of your existing song.',
    remixPackageTagline: 'Transform your song with modern production techniques.',
    giftPackageDesc: 'Personalized musical gift with beautiful presentation.',
    giftPackageTagline: 'The perfect surprise for your loved ones with elegant delivery.',
    
    // Form Fields
    recipientName: 'Name of the person the song is for',
    relationship: 'Your relationship with this person',
    occasion: 'Occasion (birthday, wedding, etc.)',
    eventDate: 'Event date',
    songLanguage: 'Language you want the song written in',
    pronunciationAudioRecipient: 'Audio recording (if the name has special pronunciation)',
    story: 'The story you want us to transform into a song',
    emotionalTone: 'Song tone (romantic, cheerful, nostalgic, etc.)',
    keyMoments: 'Essential moments from your relationship',
    specialWords: 'Words/expressions that should appear',
    pronunciationAudioKeywords: 'Audio recording for difficult words',
    musicStyle: 'What music style do you prefer',
    referenceSong: 'Example song with similar vibe',
    fullName: 'Your full name',
    email: 'Your email address',
    phone: 'Phone number (optional)',
    acceptMentionObligation: 'I accept that if I publish the song, I must mention "MusicGift.ro by Mango Records"',
    
    // Business Package Fields
    brandName: 'Brand/Company name',
    campaignPurpose: 'Campaign purpose and target audience',
    brandValues: 'Brand values and desired message',
    
    // Artist Package Fields
    artistName: 'Artist/Band name',
    songStyle: 'Desired musical style',
    artistBio: 'Artist bio and musical background',
    linksReleases: 'Links to previous releases',
    linksMedia: 'Links to social media/press',
    
    // Gift Package Fields
    recipientEmail: 'Recipient email address',
    giftMessage: 'Personal message for recipient',
    
    // Instrumental Package Fields
    desiredStyle: 'Desired musical style/genre',
    instrumentalReference: 'Reference track or description',
    
    // Remix Package Fields
    originalTitle: 'Original song title',
    originalArtist: 'Original artist',
    
    // Relationships
    partner: 'Partner/Wife/Husband',
    child: 'Child',
    parent: 'Parent',
    sibling: 'Brother/Sister',
    friend: 'Friend',
    grandparent: 'Grandparent',
    otherRelation: 'Other relationship',
    
    // Occasions
    birthday: 'Birthday',
    wedding: 'Wedding',
    anniversary: 'Anniversary',
    valentine: 'Valentine\'s Day',
    graduation: 'Graduation',
    christmas: 'Christmas',
    otherOccasion: 'Other occasion',
    
    // Emotional Tones
    romantic: 'Romantic',
    happy: 'Happy/Joyful',
    nostalgic: 'Nostalgic',
    emotional: 'Emotional',
    energetic: 'Energetic',
    peaceful: 'Peaceful/Calm',
    
    // Music Styles
    pop: 'Pop',
    acoustic: 'Acoustic',
    rock: 'Rock',
    jazz: 'Jazz',
    folk: 'Folk',
    electronic: 'Electronic',
    classical: 'Classical',
    reggae: 'Reggae',
    country: 'Country',
    
    // Languages
    romanian: 'Romanian',
    english: 'English',
    french: 'French',
    german: 'German',
    polish: 'Polish',
    
    // Addons
    rushDelivery: 'Priority delivery in 24-48h',
    commercialRights: 'Commercial rights for YouTube, Spotify etc.',
    distributionMangoRecords: 'Official distribution through Mango Records',
    customVideo: 'Custom video with your photos',
    audioMessageFromSender: 'Personal audio message incorporated into the song',
    extendedSong: 'Extended song with 3 verses instead of 2',
    
    // Audio Recording
    startRecording: 'Start recording',
    stopRecording: 'Stop recording',
    play: 'Play',
    pause: 'Pause',
    reRecord: 'Record again',
    recordingSuccessfullySaved: 'Audio recording saved successfully',
    recordingTimeLimit: 'Time limit: {time} seconds. Record the correct pronunciation.',
    recordPersonalMessage: 'Record your personal audio message',
    personalMessageLimit: 'Time limit: 45 seconds. Your message will be incorporated into the final song.',
    uploadImagesVideo: 'Upload images or video for the custom video',
    acceptImagesVideo: 'We accept images (JPG, PNG) and video (MP4, MOV). You can select multiple files.',
    cannotSelectWith: 'Cannot be selected with',
    
    // Required Field Indicator
    required: '*',
    
    // Delivery Times
    deliveryTime3to5: '3-5 days',
    deliveryTime5to7: '5-7 days',
    deliveryTime7to10: '7-10 days',
    deliveryTime14to21: '14-21 days',
    deliveryTimeVaries: 'Varies by selected package',
    
    // Package Prices
    price599: '599 RON',
    price1299: '1299 RON',
    price2499: '2499 RON',
    price3999: '3999 RON',
    price799: '799 RON',
    price999: '999 RON',
    price699: '699 RON',
    
    // Package Includes
    originalSongFromStory: 'Original song created from your story',
    professionalVoice: 'Professional voice from MusicGift team',
    rapidDelivery: 'Rapid delivery in 3-5 days',
    personalRights: 'Personal use rights (non-commercial)',
    creativeConsultation: 'Creative consultation based on story and musical preferences',
    commercialSong: 'Commercial song for brand/company',
    professionalAudioProduction: 'Professional audio production',
    professionalArtistVoice: 'Voice recorded by professional artist',
    finalMixMaster: 'Final mix and master',
    basicCommercialRights: 'Basic commercial rights included',
    multipleAudioFiles: 'Multiple audio files (WAV, MP3, instrumental)',
    premiumAdvancedProduction: 'Premium song with advanced production',
    automaticDigitalDistribution: 'Automatic distribution on digital platforms',
    lyricVideoIncluded: 'Lyric video included',
    professionalMixMaster: 'Professional mix and master',
    socialMediaPromotion: 'Social media promotion on Mango Records',
    fullArtisticCollaboration: 'Full artistic collaboration',
    originalSongProduction: 'Original song production',
    professionalVocalRecording: 'Professional vocal recording',
    professionalMusicVideo: 'Professional music video',
    distributionAllPlatforms: 'Distribution on all platforms',
    contract5050: '50/50 contract with Mango Records',
    professionalMarketing: 'Professional promotion and marketing',
    customInstrumental: 'Custom instrumental in desired genre',
    separateStems: 'Separate stems for mixing',
    professionalRemix: 'Professional remix of your song',
    productionDesiredStyle: 'Production in desired style',
    extendedRadioEdit: 'Extended version and radio edit',
    highQualityAudioFiles: 'High quality audio files',
    personalizedDigitalCard: 'Personalized digital gift card',
    personalizedMessage: 'Personalized message for recipient',
    automaticDelivery: 'Automatic delivery at desired date',
    allSelectedPackageBenefits: 'All benefits of selected package'
  },
  ro: {
    // Navigation
    home: 'Acasă',
    about: 'Despre Noi',
    packages: 'Pachete',
    howItWorks: 'Cum Funcționează',
    testimonials: 'Testimoniale',
    contact: 'Contact',
    orderNow: 'Comandă Acum',
    signIn: 'Conectează-te',
    user: 'Utilizator',
    accountSettings: 'Setări cont',
    signOut: 'Deconectează-te',
    
    // Order Page
    placeOrder: 'Plasează Comanda',
    orderSubtitle: 'Să creăm ceva magic împreună. Completează formularul de mai jos pentru a începe.',
    orderSent: 'Comandă trimisă!',
    orderThankYou: 'Mulțumim pentru comandă. Vă vom contacta în curând pentru confirmarea detaliilor.',
    orderError: 'Eroare',
    orderErrorMessage: 'A apărut o eroare la salvarea comenzii. Încercați din nou.',
    
    // Order Form Navigation
    backToHome: 'Înapoi Acasă',
    progress: 'Progres',
    previous: 'ANTERIOR',
    continue: 'CONTINUĂ',
    completeOrder: 'FINALIZEAZĂ COMANDA',
    submitting: 'SE TRIMITE...',
    of: 'din',
    
    // Order Form Validation
    completeRequiredFields: 'Te rugăm să completezi toate câmpurile obligatorii',
    completeRequiredFieldsDesc: 'Asigură-te că completezi toate informațiile necesare înainte de a continua.',
    orderSubmittedSuccess: 'Comanda a fost trimisă cu succes!',
    orderSubmittedDesc: 'Mulțumim pentru comandă. Te vom contacta în curând cu următorii pași.',
    somethingWentWrong: 'Ceva nu a mers bine',
    tryAgainSupport: 'Te rugăm să încerci din nou sau să contactezi suportul dacă problema persistă.',
    
    // Step Titles
    stepPackage: 'Pachet',
    stepDetails: 'Detalii',
    stepStory: 'Poveste',
    stepPreferences: 'Preferințe',
    stepContact: 'Contact',
    
    // Step Configuration
    choosePackage: 'Alege pachetul',
    generalDetails: 'Detalii generale',
    storyAndEmotionalDetails: 'Poveste și detalii emoționale',
    musicalPreferences: 'Preferințe muzicale',
    confirmation: 'Confirmare',
    
    // Package Details
    whatsIncluded: 'Ce include:',
    professionalQuality: 'Calitate profesională garantată',
    professionalQualityGuaranteed: 'Calitate Profesională Garantată',
    tellUsAboutRecipient: 'Spune-ne despre destinatar',
    helpUnderstand: 'Ajută-ne să înțelegem pentru cine este această melodie specială și ce ocazie sărbătorim.',
    
    // Order Summary
    orderSummary: 'Sumar Comandă',
    package: 'Pachet',
    delivery: 'Livrare',
    selectedAddons: 'Extra-uri Selectate',
    total: 'Total',
    
    // Help Section
    needHelp: 'Ai nevoie de ajutor?',
    mondayToFriday: 'Lun-Vin: 9:00-18:00',
    
    // Testimonial Section
    testimonialQuote: '"Să lucrez cu MusicGift a fost minunat. Au înțeles perfect povestea noastră și au creat ceva magic!"',
    testimonialAuthor: '— Radu & Elena',
    
    // Packages
    personalPackage: 'Pachet Personal',
    businessPackage: 'Pachet Business',
    premiumPackage: 'Pachet Premium',
    artistPackage: 'Pachet Artist',
    instrumentalPackage: 'Pachet Instrumental',
    remixPackage: 'Pachet Remix',
    giftPackage: 'Pachet Cadou',
    
    // Package Descriptions
    personalPackageDesc: 'Un cântec scris cu suflet – doar pentru tine și cei dragi.',
    personalPackageTagline: 'Ideal pentru aniversări, nunți sau ocazii speciale – transformăm povestea ta într-un cadou muzical unic și emoționant.',
    businessPackageDesc: 'Melodii comerciale profesionale pentru branduri și companii.',
    businessPackageTagline: 'Perfect pentru campanii publicitare, imnuri de brand sau evenimente corporative.',
    premiumPackageDesc: 'Melodie premium cu producție avansată și distribuție.',
    premiumPackageTagline: 'Distribuție profesională pe toate platformele cu suport promoțional.',
    artistPackageDesc: 'Colaborare artistică completă pentru muzicienii aspiranți.',
    artistPackageTagline: 'Producție muzicală completă cu videoclip profesional și marketing.',
    instrumentalPackageDesc: 'Muzică instrumentală personalizată în genul dorit.',
    instrumentalPackageTagline: 'Perfect pentru creatorii de conținut, podcasturi sau muzică de fundal.',
    remixPackageDesc: 'Remix profesional al piesei tale existente.',
    remixPackageTagline: 'Transformă-ți piesa cu tehnici moderne de producție.',
    giftPackageDesc: 'Cadou muzical personalizat cu prezentare frumoasă.',
    giftPackageTagline: 'Surpriza perfectă pentru cei dragi cu livrare elegantă.',
    
    // Form Fields
    recipientName: 'Numele persoanei pentru care este melodia',
    relationship: 'Relația ta cu această persoană',
    occasion: 'Ocazie (zi de naștere, nuntă etc.)',
    eventDate: 'Data evenimentului',
    songLanguage: 'Limba în care vrei să fie scrisă piesa',
    pronunciationAudioRecipient: 'Înregistrare audio (dacă numele are pronunție specială)',
    story: 'Povestea pe care vrei să o transformăm în cântec',
    emotionalTone: 'Tonul piesei (romantic, vesel, nostalgic etc.)',
    keyMoments: 'Momente esențiale din relația voastră',
    specialWords: 'Cuvinte/expresii care ar trebui să apară',
    pronunciationAudioKeywords: 'Înregistrare audio pentru cuvinte dificile',
    musicStyle: 'Ce stil muzical preferi',
    referenceSong: 'Exemplu de piesă cu vibe similar',
    fullName: 'Numele tău complet',
    email: 'Adresa ta de e-mail',
    phone: 'Număr de telefon (opțional)',
    acceptMentionObligation: 'Accept că dacă public piesa, trebuie să menționez "MusicGift.ro by Mango Records"',
    
    // Business Package Fields
    brandName: 'Numele brandului/companiei',
    campaignPurpose: 'Scopul campaniei și publicul țintă',
    brandValues: 'Valorile brandului și mesajul dorit',
    
    // Artist Package Fields
    artistName: 'Numele artistului/trupei',
    songStyle: 'Stilul muzical dorit',
    artistBio: 'Bio artistului și fundalul muzical',
    linksReleases: 'Link-uri către lansările anterioare',
    linksMedia: 'Link-uri către rețelele sociale/presă',
    
    // Gift Package Fields
    recipientEmail: 'Adresa de email a destinatarului',
    giftMessage: 'Mesaj personal pentru destinatar',
    
    // Instrumental Package Fields
    desiredStyle: 'Stilul/genul muzical dorit',
    instrumentalReference: 'Piesă de referință sau descriere',
    
    // Remix Package Fields
    originalTitle: 'Titlul piesei originale',
    originalArtist: 'Artistul original',
    
    // Relationships
    partner: 'Partener/Soție/Soț',
    child: 'Copil',
    parent: 'Părinte',
    sibling: 'Frate/Soră',
    friend: 'Prieten(ă)',
    grandparent: 'Bunic/Bunică',
    otherRelation: 'Altă relație',
    
    // Occasions
    birthday: 'Zi de naștere',
    wedding: 'Nuntă',
    anniversary: 'Aniversare',
    valentine: 'Ziua Îndrăgostiților',
    graduation: 'Absolvire',
    christmas: 'Crăciun',
    otherOccasion: 'Altă ocazie',
    
    // Emotional Tones
    romantic: 'Romantic',
    happy: 'Vesel/Bucuros',
    nostalgic: 'Nostalgic',
    emotional: 'Emoționant',
    energetic: 'Energic',
    peaceful: 'Liniștit/Calm',
    
    // Music Styles
    pop: 'Pop',
    acoustic: 'Acustic',
    rock: 'Rock',
    jazz: 'Jazz',
    folk: 'Folk',
    electronic: 'Electronic',
    classical: 'Clasic',
    reggae: 'Reggae',
    country: 'Country',
    
    // Languages
    romanian: 'Română',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    polish: 'Polski',
    
    // Addons
    rushDelivery: 'Livrare prioritară în 24–48h',
    commercialRights: 'Drepturi comerciale pentru YouTube, Spotify etc.',
    distributionMangoRecords: 'Distribuție oficială prin Mango Records',
    customVideo: 'Videoclip personalizat cu pozele tale',
    audioMessageFromSender: 'Mesaj audio personalizat încorporat în piesă',
    extendedSong: 'Melodie extinsă cu 3 strofe în loc de 2',
    
    // Audio Recording
    startRecording: 'Începe înregistrarea',
    stopRecording: 'Oprește înregistrarea',
    play: 'Redă',
    pause: 'Pauză',
    reRecord: 'Înregistrează din nou',
    recordingSuccessfullySaved: 'Înregistrarea audio a fost salvată cu succes',
    recordingTimeLimit: 'Limita de timp: {time} secunde. Înregistrează pronunția corectă.',
    recordPersonalMessage: 'Înregistrează mesajul tău audio personal',
    personalMessageLimit: 'Limita de timp: 45 secunde. Mesajul tău va fi incorporat în piesa finală.',
    uploadImagesVideo: 'Încarcă imagini sau video pentru videoclipul personalizat',
    acceptImagesVideo: 'Acceptăm imagini (JPG, PNG) și video (MP4, MOV). Poți selecta mai multe fișiere.',
    cannotSelectWith: 'Nu poate fi selectat cu',
    
    // Required Field Indicator
    required: '*',
    
    // Delivery Times
    deliveryTime3to5: '3-5 zile',
    deliveryTime5to7: '5-7 zile',
    deliveryTime7to10: '7-10 zile',
    deliveryTime14to21: '14-21 zile',
    deliveryTimeVaries: 'Conform pachetului ales',
    
    // Package Prices
    price599: '599 RON',
    price1299: '1299 RON',
    price2499: '2499 RON',
    price3999: '3999 RON',
    price799: '799 RON',
    price999: '999 RON',
    price699: '699 RON',
    
    // Package Includes
    originalSongFromStory: 'Cântec original creat după povestea ta',
    professionalVoice: 'Voce profesionistă din echipa MusicGift',
    rapidDelivery: 'Livrare rapidă în 3–5 zile',
    personalRights: 'Drepturi de utilizare personală (non-comercial)',
    creativeConsultation: 'Consultare creativă bazată pe poveste și preferințe muzicale',
    commercialSong: 'Melodie comercială pentru brand/companie',
    professionalAudioProduction: 'Producție audio profesională',
    professionalArtistVoice: 'Voce înregistrată de artist profesionist',
    finalMixMaster: 'Mix și master final',
    basicCommercialRights: 'Drepturi comerciale de bază incluse',
    multipleAudioFiles: 'Fișiere audio multiple (WAV, MP3, instrumental)',
    premiumAdvancedProduction: 'Melodie premium cu producție avansată',
    automaticDigitalDistribution: 'Distribuție automată pe platforme digitale',
    lyricVideoIncluded: 'Videoclip lyric inclus',
    professionalMixMaster: 'Mix și master profesional',
    socialMediaPromotion: 'Promovare pe rețelele sociale Mango Records',
    fullArtisticCollaboration: 'Colaborare artistică completă',
    originalSongProduction: 'Producția unei melodii originale',
    professionalVocalRecording: 'Înregistrare vocală profesională',
    professionalMusicVideo: 'Videoclip muzical profesional',
    distributionAllPlatforms: 'Distribuție pe toate platformele',
    contract5050: 'Contract 50/50 cu Mango Records',
    professionalMarketing: 'Promovare și marketing profesional',
    customInstrumental: 'Instrumental personalizat în genul dorit',
    separateStems: 'Stems separate pentru mixing',
    professionalRemix: 'Remix profesional al piesei tale',
    productionDesiredStyle: 'Producție în stilul dorit',
    extendedRadioEdit: 'Versiune extended și radio edit',
    highQualityAudioFiles: 'Fișiere audio de înaltă calitate',
    personalizedDigitalCard: 'Card cadou digital personalizat',
    personalizedMessage: 'Mesaj personalizat pentru destinatar',
    automaticDelivery: 'Trimitere automată la data dorită',
    allSelectedPackageBenefits: 'Toate beneficiile pachetului selectat'
  },
  fr: {
    home: 'Accueil',
    about: 'À Propos',
    packages: 'Forfaits',
    howItWorks: 'Comment Ça Marche',
    testimonials: 'Témoignages',
    contact: 'Contact',
    orderNow: 'Commander',
    signIn: 'Se connecter',
    user: 'Utilisateur',
    accountSettings: 'Paramètres du compte',
    signOut: 'Se déconnecter',
    placeOrder: 'Passer Commande',
    orderSubtitle: 'Créons quelque chose de magique ensemble. Remplissez le formulaire ci-dessous pour commencer.',
    orderSent: 'Commande envoyée!',
    orderThankYou: 'Merci pour votre commande. Nous vous contacterons bientôt pour confirmer les détails.',
    orderError: 'Erreur',
    orderErrorMessage: 'Une erreur s\'est produite lors de l\'enregistrement de la commande. Veuillez réessayer.',
    backToHome: 'Retour à l\'accueil',
    progress: 'Progrès',
    previous: 'PRÉCÉDENT',
    continue: 'CONTINUER',
    completeOrder: 'FINALISER LA COMMANDE',
    submitting: 'ENVOI EN COURS...',
    of: 'de',
    stepPackage: 'Forfait',
    stepDetails: 'Détails',
    stepStory: 'Histoire',
    stepPreferences: 'Préférences',
    stepContact: 'Contact',
    personalPackage: 'Forfait Personnel',
    businessPackage: 'Forfait Entreprise',
    premiumPackage: 'Forfait Premium',
    artistPackage: 'Forfait Artiste',
    instrumentalPackage: 'Forfait Instrumental',
    remixPackage: 'Forfait Remix',
    giftPackage: 'Forfait Cadeau',
    required: '*',
    completeRequiredFields: 'Veuillez remplir tous les champs obligatoires',
    completeRequiredFieldsDesc: 'Assurez-vous de remplir toutes les informations nécessaires avant de continuer.',
    orderSubmittedSuccess: 'Commande soumise avec succès!',
    orderSubmittedDesc: 'Merci pour votre commande. Nous vous contactons bientôt avec les prochaines étapes.',
    somethingWentWrong: 'Quelque chose s\'est mal passé',
    tryAgainSupport: 'Veuillez réessayer ou contacter le support si le problème persiste.',
    choosePackage: 'Choisir le forfait',
    generalDetails: 'Détails généraux',
    storyAndEmotionalDetails: 'Histoire et détails émotionnels',
    musicalPreferences: 'Préférences musicales',
    confirmation: 'Confirmation',
    whatsIncluded: 'Ce qui est inclus:',
    professionalQuality: 'Qualité professionnelle garantie',
    professionalQualityGuaranteed: 'Qualité Professionnelle Garantie',
    tellUsAboutRecipient: 'Parlez-nous du destinataire',
    helpUnderstand: 'Aidez-nous à comprendre pour qui est cette chanson spéciale et quelle occasion nous célébrons.',
    orderSummary: 'Résumé de Commande',
    package: 'Forfait',
    delivery: 'Livraison',
    selectedAddons: 'Options Sélectionnées',
    total: 'Total',
    needHelp: 'Besoin d\'aide?',
    mondayToFriday: 'Lun-Ven: 9h-18h',
    testimonialQuote: '"Travailler avec MusicGift était incroyable. Ils ont parfaitement compris notre histoire et ont créé quelque chose de magique!"',
    testimonialAuthor: '— Radu & Elena',
    price599: '599 RON',
    price1299: '1299 RON',
    price2499: '2499 RON',
    price3999: '3999 RON',
    price799: '799 RON',
    price999: '999 RON',
    price699: '699 RON',
    deliveryTime3to5: '3-5 jours',
    deliveryTime5to7: '5-7 jours',
    deliveryTime7to10: '7-10 jours',
    deliveryTime14to21: '14-21 jours',
    deliveryTimeVaries: 'Selon le forfait sélectionné',
    personalPackageDesc: 'Une chanson écrite avec âme – juste pour vous et vos proches.',
    personalPackageTagline: 'Idéal pour les anniversaires, mariages ou occasions spéciales.',
    businessPackageDesc: 'Chansons commerciales professionnelles pour marques et entreprises.',
    businessPackageTagline: 'Parfait pour les campagnes publicitaires ou événements corporatifs.',
    premiumPackageDesc: 'Chanson premium avec production avancée et distribution.',
    premiumPackageTagline: 'Distribution professionnelle sur toutes les plateformes.',
    artistPackageDesc: 'Collaboration artistique complète pour musiciens aspirants.',
    artistPackageTagline: 'Production musicale complète avec vidéo et marketing professionnels.',
    instrumentalPackageDesc: 'Musique instrumentale personnalisée dans le genre désiré.',
    instrumentalPackageTagline: 'Parfait pour créateurs de contenu ou musique de fond.',
    remixPackageDesc: 'Remix professionnel de votre chanson existante.',
    remixPackageTagline: 'Transformez votre chanson avec des techniques modernes.',
    giftPackageDesc: 'Cadeau musical personnalisé avec belle présentation.',
    giftPackageTagline: 'La surprise parfaite avec livraison élégante.',
    originalSongFromStory: 'Chanson originale créée à partir de votre histoire',
    professionalVoice: 'Voix professionnelle de l\'équipe MusicGift',
    rapidDelivery: 'Livraison rapide en 3-5 jours',
    personalRights: 'Droits d\'usage personnel (non-commercial)',
    creativeConsultation: 'Consultation créative basée sur l\'histoire et les préférences musicales'
  },
  pl: {
    home: 'Strona Główna',
    about: 'O Nas',
    packages: 'Pakiety',
    howItWorks: 'Jak To Działa',
    testimonials: 'Opinie',
    contact: 'Kontakt',
    orderNow: 'Zamów Teraz',
    signIn: 'Zaloguj się',
    user: 'Użytkownik',
    accountSettings: 'Ustawienia konta',
    signOut: 'Wyloguj się',
    placeOrder: 'Złóż Zamówienie',
    orderSubtitle: 'Stwórzmy razem coś magicznego. Wypełnij formularz poniżej, aby rozpocząć.',
    orderSent: 'Zamówienie wysłane!',
    orderThankYou: 'Dziękujemy za zamówienie. Skontaktujemy się z Tobą wkrótce, aby potwierdzić szczegóły.',
    orderError: 'Błąd',
    orderErrorMessage: 'Wystąpił błąd podczas zapisywania zamówienia. Spróbuj ponownie.',
    backToHome: 'Powrót do domu',
    progress: 'Postęp',
    previous: 'POPRZEDNI',
    continue: 'KONTYNUUJ',
    completeOrder: 'ZAKOŃCZ ZAMÓWIENIE',
    submitting: 'WYSYŁANIE...',
    of: 'z',
    stepPackage: 'Pakiet',
    stepDetails: 'Szczegóły',
    stepStory: 'Historia',
    stepPreferences: 'Preferencje',
    stepContact: 'Kontakt',
    personalPackage: 'Pakiet Osobisty',
    businessPackage: 'Pakiet Biznesowy',
    premiumPackage: 'Pakiet Premium',
    artistPackage: 'Pakiet Artysty',
    instrumentalPackage: 'Pakiet Instrumentalny',
    remixPackage: 'Pakiet Remix',
    giftPackage: 'Pakiet Prezentowy',
    required: '*',
    completeRequiredFields: 'Proszę wypełnić wszystkie wymagane pola',
    completeRequiredFieldsDesc: 'Upewnij się, że wypełniłeś wszystkie niezbędne informacje przed kontynuowaniem.',
    orderSubmittedSuccess: 'Zamówienie zostało złożone pomyślnie!',
    orderSubmittedDesc: 'Dziękujemy za zamówienie. Skontaktujemy się z Tobą wkrótce z następnymi krokami.',
    somethingWentWrong: 'Coś poszło nie tak',
    tryAgainSupport: 'Spróbuj ponownie lub skontaktuj się z pomocą techniczną, jeśli problem będzie się powtarzał.',
    choosePackage: 'Wybierz pakiet',
    generalDetails: 'Szczegóły ogólne',
    storyAndEmotionalDetails: 'Historia i szczegóły emocjonalne',
    musicalPreferences: 'Preferencje muzyczne',
    confirmation: 'Potwierdzenie',
    whatsIncluded: 'Co jest zawarte:',
    professionalQuality: 'Gwarantowana jakość profesjonalna',
    professionalQualityGuaranteed: 'Gwarantowana Jakość Profesjonalna',
    tellUsAboutRecipient: 'Opowiedz nam o odbiorcy',
    helpUnderstand: 'Pomóż nam zrozumieć, dla kogo jest ta specjalna piosenka i jaką okazję świętujemy.',
    orderSummary: 'Podsumowanie Zamówienia',
    package: 'Pakiet',
    delivery: 'Dostawa',
    selectedAddons: 'Wybrane Dodatki',
    total: 'Razem',
    needHelp: 'Potrzebujesz pomocy?',
    mondayToFriday: 'Pon-Pt: 9:00-18:00',
    testimonialQuote: '"Praca z MusicGift była niesamowita. Doskonale zrozumieli naszą historię i stworzyli coś magicznego!"',
    testimonialAuthor: '— Radu & Elena',
    price599: '599 RON',
    price1299: '1299 RON',
    price2499: '2499 RON',
    price3999: '3999 RON',
    price799: '799 RON',
    price999: '999 RON',
    price699: '699 RON',
    deliveryTime3to5: '3-5 dni',
    deliveryTime5to7: '5-7 dni',
    deliveryTime7to10: '7-10 dni',
    deliveryTime14to21: '14-21 dni',
    deliveryTimeVaries: 'Zgodnie z wybranym pakietem',
    personalPackageDesc: 'Piosenka napisana z duszą – tylko dla Ciebie i Twoich bliskich.',
    personalPackageTagline: 'Idealna na urodziny, wesela lub specjalne okazje.',
    businessPackageDesc: 'Profesjonalne piosenki komercyjne dla marek i firm.',
    businessPackageTagline: 'Idealne do kampanii reklamowych lub wydarzeń korporacyjnych.',
    premiumPackageDesc: 'Piosenka premium z zaawansowaną produkcją i dystrybucją.',
    premiumPackageTagline: 'Profesjonalna dystrybucja na wszystkich platformach.',
    artistPackageDesc: 'Pełna współpraca artystyczna dla aspirujących muzyków.',
    artistPackageTagline: 'Kompletna produkcja muzyczna z profesjonalnym wideo i marketingiem.',
    instrumentalPackageDesc: 'Spersonalizowana muzyka instrumentalna w pożądanym gatunku.',
    instrumentalPackageTagline: 'Idealna dla twórców treści lub muzyki tła.',
    remixPackageDesc: 'Profesjonalny remix Twojej istniejącej piosenki.',
    remixPackageTagline: 'Przekształć swoją piosenkę nowoczesnymi technikami.',
    giftPackageDesc: 'Spersonalizowany prezent muzyczny z piękną prezentacją.',
    giftPackageTagline: 'Idealna niespodzianka z elegancką dostawą.',
    originalSongFromStory: 'Oryginalna piosenka stworzona z Twojej historii',
    professionalVoice: 'Profesjonalny głos z zespołu MusicGift',
    rapidDelivery: 'Szybka dostawa w 3-5 dni',
    personalRights: 'Prawa do użytku osobistego (niekomercyjne)',
    creativeConsultation: 'Konsultacja kreatywna oparta na historii i preferencjach muzycznych'
  },
  de: {
    home: 'Startseite',
    about: 'Über Uns',
    packages: 'Pakete',
    howItWorks: 'Wie Es Funktioniert',
    testimonials: 'Bewertungen',
    contact: 'Kontakt',
    orderNow: 'Jetzt Bestellen',
    signIn: 'Anmelden',
    user: 'Benutzer',
    accountSettings: 'Kontoeinstellungen',
    signOut: 'Abmelden',
    placeOrder: 'Bestellung Aufgeben',
    orderSubtitle: 'Lassen Sie uns gemeinsam etwas Magisches schaffen. Füllen Sie das untenstehende Formular aus, um zu beginnen.',
    orderSent: 'Bestellung gesendet!',
    orderThankYou: 'Vielen Dank für Ihre Bestellung. Wir werden Sie bald kontaktieren, um die Details zu bestätigen.',
    orderError: 'Fehler',
    orderErrorMessage: 'Beim Speichern der Bestellung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    backToHome: 'Zurück zur Startseite',
    progress: 'Fortschritt',
    previous: 'ZURÜCK',
    continue: 'WEITER',
    completeOrder: 'BESTELLUNG ABSCHLIESSEN',
    submitting: 'WIRD GESENDET...',
    of: 'von',
    stepPackage: 'Paket',
    stepDetails: 'Details',
    stepStory: 'Geschichte',
    stepPreferences: 'Präferenzen',
    stepContact: 'Kontakt',
    personalPackage: 'Persönliches Paket',
    businessPackage: 'Business Paket',
    premiumPackage: 'Premium Paket',
    artistPackage: 'Künstler Paket',
    instrumentalPackage: 'Instrumental Paket',
    remixPackage: 'Remix Paket',
    giftPackage: 'Geschenk Paket',
    required: '*',
    completeRequiredFields: 'Bitte füllen Sie alle Pflichtfelder aus',
    completeRequiredFieldsDesc: 'Stellen Sie sicher, dass Sie alle erforderlichen Informationen eingeben, bevor Sie fortfahren.',
    orderSubmittedSuccess: 'Bestellung erfolgreich übermittelt!',
    orderSubmittedDesc: 'Vielen Dank für Ihre Bestellung. Wir werden Sie bald mit den nächsten Schritten kontaktieren.',
    somethingWentWrong: 'Etwas ist schiefgelaufen',
    tryAgainSupport: 'Bitte versuchen Sie es erneut oder kontaktieren Sie den Support, wenn das Problem weiterhin besteht.',
    choosePackage: 'Paket wählen',
    generalDetails: 'Allgemeine Details',
    storyAndEmotionalDetails: 'Geschichte und emotionale Details',
    musicalPreferences: 'Musikalische Präferenzen',
    confirmation: 'Bestätigung',
    whatsIncluded: 'Was ist enthalten:',
    professionalQuality: 'Professionelle Qualität garantiert',
    professionalQualityGuaranteed: 'Professionelle Qualität Garantiert',
    tellUsAboutRecipient: 'Erzählen Sie uns über den Empfänger',
    helpUnderstand: 'Helfen Sie uns zu verstehen, für wen dieses besondere Lied ist und welchen Anlass wir feiern.',
    orderSummary: 'Bestellübersicht',
    package: 'Paket',
    delivery: 'Lieferung',
    selectedAddons: 'Ausgewählte Extras',
    total: 'Gesamt',
    needHelp: 'Brauchen Sie Hilfe?',
    mondayToFriday: 'Mo-Fr: 9:00-18:00',
    testimonialQuote: '"Mit MusicGift zu arbeiten war erstaunlich. Sie haben unsere Geschichte perfekt verstanden und etwas Magisches geschaffen!"',
    testimonialAuthor: '— Radu & Elena',
    price599: '599 RON',
    price1299: '1299 RON',
    price2499: '2499 RON',
    price3999: '3999 RON',
    price799: '799 RON',
    price999: '999 RON',
    price699: '699 RON',
    deliveryTime3to5: '3-5 Tage',
    deliveryTime5to7: '5-7 Tage',
    deliveryTime7to10: '7-10 Tage',
    deliveryTime14to21: '14-21 Tage',
    deliveryTimeVaries: 'Je nach gewähltem Paket',
    personalPackageDesc: 'Ein Lied mit Seele geschrieben – nur für Sie und Ihre Lieben.',
    personalPackageTagline: 'Ideal für Geburtstage, Hochzeiten oder besondere Anlässe.',
    businessPackageDesc: 'Professionelle kommerzielle Lieder für Marken und Unternehmen.',
    businessPackageTagline: 'Perfekt für Werbekampagnen oder Unternehmensveranstaltungen.',
    premiumPackageDesc: 'Premium-Lied mit fortschrittlicher Produktion und Vertrieb.',
    premiumPackageTagline: 'Professioneller Vertrieb auf allen Plattformen.',
    artistPackageDesc: 'Vollständige künstlerische Zusammenarbeit für aufstrebende Musiker.',
    artistPackageTagline: 'Komplette Musikproduktion mit professionellem Video und Marketing.',
    instrumentalPackageDesc: 'Maßgeschneiderte Instrumentalmusik im gewünschten Genre.',
    instrumentalPackageTagline: 'Perfekt für Content-Ersteller oder Hintergrundmusik.',
    remixPackageDesc: 'Professioneller Remix Ihres bestehenden Liedes.',
    remixPackageTagline: 'Verwandeln Sie Ihr Lied mit modernen Produktionstechniken.',
    giftPackageDesc: 'Personalisiertes Musikgeschenk mit schöner Präsentation.',
    giftPackageTagline: 'Die perfekte Überraschung mit eleganter Lieferung.',
    originalSongFromStory: 'Originallied aus Ihrer Geschichte erstellt',
    professionalVoice: 'Professionelle Stimme vom MusicGift-Team',
    rapidDelivery: 'Schnelle Lieferung in 3-5 Tagen',
    personalRights: 'Persönliche Nutzungsrechte (nicht-kommerziell)',
    creativeConsultation: 'Kreative Beratung basierend auf Geschichte und musikalischen Präferenzen'
  }
};

const languageNames = {
  en: 'EN',
  ro: 'RO',
  fr: 'FR',
  pl: 'PL',
  de: 'DE'
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('ro');

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languageNames };
