import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ro' | 'fr' | 'pl' | 'de';

interface LanguageContextType {
  currentLanguage: Language;
  setCurrentLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About Us',
    packages: 'Packages',
    howItWorks: 'How It Works',
    testimonials: 'Testimonials',
    contact: 'Contact',
    orderNow: 'Order Now',
    signIn: 'Sign In',
    user: 'User',
    accountSettings: 'Account Settings',
    signOut: 'Sign Out',
    
    // Common
    selectLanguage: 'Select language',
    selectOption: 'Select an option',
    selectYourPackage: 'Select Your Package',
    loadingPackages: 'Loading packages...',
    mostPopular: 'Most Popular',
    
    // Home Page
    heroTitle: 'Give the Gift of Music',
    heroSubtitle: 'A personalized song, created just for your special someone. The most unique gift they\'ll ever receive.',
    seePackages: 'See Packages',
    listenToSamples: 'Listen to Samples',
    whatIsMusicGiftFor: 'What is MusicGift for?',
    marriageProposals: 'Marriage Proposals',
    seeExamples: 'See examples',
    chooseYourPackage: 'Choose Your Package',
    selectPerfectPackage: 'Select the perfect music package that fits your needs and budget',
    failedToLoadPackages: 'Failed to load packages. Please try again later.',
    reload: 'Reload',
    noPackagesAvailable: 'No packages available at the moment.',
    checkBackLater: 'Please check back later.',
    viewAllPackages: 'View All Packages',
    readyToCreateSpecial: 'Ready to Create Something Special?',
    helpCreatePersonalized: 'Let us help you create a personalized musical gift that will be treasured forever.',
    startYourOrder: 'Start Your Order',
    
    // Contact Page
    contactTitle: 'Contact Us',
    contactSubtitle: 'Get in touch with us for any questions or to start your musical journey',
    getInTouch: 'Get In Touch',
    contactDescription: 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    emailUs: 'Email Us',
    callUs: 'Call Us',
    visitUs: 'Visit Us',
    followUs: 'Follow Us',
    sendMessage: 'Send Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    phoneNumber: 'Phone Number',
    yourMessage: 'Your Message',
    sendMessageBtn: 'Send Message',
    messageSent: 'Message sent!',
    messageThankYou: 'Thank you for your message. We will get back to you soon.',
    
    // Page Titles and Content
    howItWorksTitle: 'How It Works',
    howItWorksSubtitle: 'Follow these simple steps to get your personalized song',
    aboutTitle: 'About Us',
    aboutSubtitle: 'At MusicGift we believe that music is the purest form of emotion.',
    aboutNewDescription1: 'In every personal story there is an unsung song, an emotion that deserves to come to life. We transform these emotions into real melodies, created by real artists, for real people.',
    aboutNewDescription2: 'MusicGift was born from the desire to bring people a unique gift: a song created especially for them. In a world where everything becomes fast and superficial, we have chosen to invest time, soul and passion in every musical creation. Founded by Mihai Gruia, music producer and former member of the international band Akcent, MusicGift combines stage and studio experience with the sincere emotion of personal stories.',
    testimonialsTitle: 'What Our Clients Say',
    testimonialsSubtitle: 'Real stories from satisfied customers who turned their memories into music',
    packagesSubtitle: 'Select the perfect music package that fits your needs and budget',
    
    // Testimonials Page
    testimonials_page_title: 'Customer Testimonials',
    testimonials_page_description: 'Discover what our customers say about their personalized music experience',

    // Step Process
    choosePackage: 'Choose Your Package',
    choosePackageDesc: 'Select from our range of personalized music packages',
    tellYourStory: 'Tell Your Story',
    tellYourStoryDesc: 'Share the details and emotions you want captured',
    weCreate: 'We Create',
    weCreateDesc: 'Our team composes your unique musical piece',
    deliverDelight: 'Deliver & Delight',
    deliverDelightDesc: 'Receive your personalized song and cherish forever',
    
    // Team
    ourTeam: 'Our Team',
    leadComposer: 'Lead Composer',
    leadVocalist: 'Lead Vocalist',
    soundEngineer: 'Sound Engineer',
    songsCreated: 'Songs Created',
    yearsExperience: 'Years Experience',
    clientSatisfaction: 'Client Satisfaction',
    
    // Testimonials
    testimonial1: 'Working with MusicGift was amazing. They understood our story perfectly and created something magical!',
    author1: 'Maria & Alex',
    location1: 'Bucharest, Romania',
    testimonial2: 'The personalized song for our anniversary was beyond our expectations. Pure perfection!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Romania',
    testimonial3: 'Our wedding song still gives us chills every time we hear it. Thank you for this beautiful gift!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Romania',
    
    // 404 Page
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'The page you are looking for does not exist',
    returnHome: 'Return Home',
    
    // Order Page
    placeOrder: 'Place Order',
    orderSubtitle: 'Let\'s create something magical together. Fill out the form below to get started.',
    orderSent: 'Order sent!',
    orderThankYou: 'Thank you for your order. We will contact you soon to confirm the details.',
    orderError: 'Error',
    orderErrorMessage: 'An error occurred while saving the order. Please try again.',
    
    // Order Form Navigation
    backToHome: 'Back to Home',
    progress: 'Progress',
    previous: 'PREVIOUS',
    continue: 'CONTINUE',
    completeOrder: 'COMPLETE ORDER',
    submitting: 'SUBMITTING...',
    of: 'of',
    
    // Order Form Validation
    completeRequiredFields: 'Please complete all required fields',
    completeRequiredFieldsDesc: 'Make sure to fill in all required information before proceeding.',
    orderSubmittedSuccess: 'Order submitted successfully!',
    orderSubmittedDesc: 'Thank you for your order. We\'ll contact you soon with next steps.',
    somethingWentWrong: 'Something went wrong',
    tryAgainSupport: 'Please try again or contact support if the problem persists.',
    
    // Step Titles
    stepPackage: 'Package',
    stepDetails: 'Details',
    stepStory: 'Story',
    stepPreferences: 'Preferences',
    stepContact: 'Contact',
    
    // Step Configuration
    generalDetails: 'General details',
    storyAndEmotionalDetails: 'Story and emotional details',
    musicalPreferences: 'Musical preferences',
    confirmation: 'Confirmation',
    
    // Package Details
    whatsIncluded: 'What\'s included:',
    professionalQuality: 'Professional quality guaranteed',
    professionalQualityGuaranteed: 'Professional Quality Guaranteed',
    tellUsAboutRecipient: 'Tell Us About the Recipient',
    helpUnderstand: 'Help us understand who this special song is for and what occasion we\'re celebrating.',
    
    // Order Summary
    orderSummary: 'Order Summary',
    package: 'Package',
    delivery: 'Delivery',
    selectedAddons: 'Selected Addons',
    total: 'Total',
    
    // Help Section
    needHelp: 'Need Help?',
    mondayToFriday: 'Mon-Fri: 9AM-6PM',
    
    // Testimonial Section
    testimonialQuote: '"Working with MusicGift was amazing. They understood our story perfectly and created something magical!"',
    testimonialAuthor: '— Radu & Elena',
    
    // Footer
    footerDescription: 'Creating personalized musical gifts. Transform your special moments into beautiful custom songs.',
    quickLinks: 'Quick Links',
    contactInfo: 'Contact Info',
    legal: 'Legal',
    stayUpdated: 'Stay Updated',
    newsletterDescription: 'Subscribe to get special offers, new packages, and exclusive musical content delivered to your inbox.',
    enterEmail: 'Enter your email address',
    subscribe: 'Subscribe',
    subscribeDisclaimer: 'By subscribing, you agree to our Privacy Policy and consent to receive updates from our company.',
    copyright: '© 2025 MusicGift.ro. All rights reserved. Made by RED DOMAIN with ❤️ for music lovers.',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    refundPolicy: 'Refund Policy',
    cookiePolicy: 'Cookie Policy',
    admin: 'Admin',
    
    // Packages
    personalPackage: 'Personal Package',
    businessPackage: 'Business Package',
    premiumPackage: 'Premium Package',
    artistPackage: 'Artist Package',
    instrumentalPackage: 'Instrumental Package',
    remixPackage: 'Remix Package',
    giftPackage: 'Gift Package',
    
    // Package Descriptions
    personalPackageDesc: 'A song written with soul – just for you and your loved ones.',
    personalPackageTagline: 'Ideal for birthdays, weddings or special occasions – we transform your story into a unique and emotional musical gift.',
    businessPackageDesc: 'Professional commercial songs for brands and companies.',
    businessPackageTagline: 'Perfect for advertising campaigns, brand anthems, or corporate events.',
    premiumPackageDesc: 'Premium quality song with advanced production and distribution.',
    premiumPackageTagline: 'Professional distribution on all platforms with promotional support.',
    artistPackageDesc: 'Full artistic collaboration for aspiring musicians.',
    artistPackageTagline: 'Complete music production with professional video and marketing.',
    instrumentalPackageDesc: 'Custom instrumental music in your desired genre.',
    instrumentalPackageTagline: 'Perfect for content creators, podcasts, or background music.',
    remixPackageDesc: 'Professional remix of your existing song.',
    remixPackageTagline: 'Transform your song with modern production techniques.',
    giftPackageDesc: 'Personalized musical gift with beautiful presentation.',
    giftPackageTagline: 'The perfect surprise for your loved ones with elegant delivery.',
    
    // Languages
    romanian: 'Romanian',
    english: 'English',
    french: 'French',
    german: 'German',
    polish: 'Polish',

    // Who We Are Section
    whoWeAre: 'Who We Are',
    mihaiGruiaTitle: 'Mihai Gruia',
    mihaiGruiaDescription: 'Music producer and composer, founding member of Akcent – one of the most successful Romanian pop bands internationally, with famous hits like \'That\'s My Name\', \'Kylie\' and \'Stay with Me\'. After Akcent\'s success, Mihai continued his artistic career through the TWO project and got involved in music production for top artists. Today, he coordinates the MusicGift and DOMG Studio team, bringing his expertise to every delivered project.',
    mangoRecordsTitle: 'Mango Records',
    mangoRecordsDescription: 'Mango Records, founded and coordinated by Mihai Gruia, is an independent record label from Romania, specialized in launching and distributing original music internationally. It has promoted successful artists like TWO (ex-Akcent), DOMG, Mellina, Red Blonde, Pitt Leffer, Katerina and Vulgaris. With over 1000 tracks distributed globally on Spotify, Apple Music and YouTube, Mango Records actively contributes to the contemporary music scene. It has also achieved successful commercial collaborations with international brands.',
    domgStudioTitle: 'DOMG Studio',
    domgStudioDescription: 'Premium music creation studio, with compositions for top Romanian and international artists: Akcent, Andra, Lora, Alina Eremia and others. Offers impeccable audio quality and professional composition, recording and mix-master processes.',
    doMusicForGoodTitle: 'Do Music for Good Band',
    doMusicForGoodDescription: 'A team of professional performers who collaborate to bring MusicGift melodies to life. Each voice and each note are carefully chosen to authentically express the emotion conveyed by the client.',
  },
  ro: {
    // Navigation
    home: 'Acasă',
    about: 'Despre Noi',
    packages: 'Pachete',
    howItWorks: 'Cum Funcționează',
    testimonials: 'Testimoniale',
    contact: 'Contact',
    orderNow: 'Comandă Acum',
    signIn: 'Conectează-te',
    user: 'Utilizator',
    accountSettings: 'Setări cont',
    signOut: 'Deconectează-te',
    
    // Common
    selectLanguage: 'Selectează limba',
    selectOption: 'Selectează o opțiune',
    selectYourPackage: 'Selectează Pachetul',
    loadingPackages: 'Se încarcă pachetele...',
    mostPopular: 'Cel Mai Popular',
    
    // Home Page - Updated content
    heroTitle: 'Transformă Emoțiile Tale în Muzică',
    heroSubtitle: 'Cel mai frumos cadou: o melodie creată special pentru cineva drag.',
    seePackages: 'Vezi Pachetele',
    listenToSamples: 'Ascultă Mostre',
    whatIsMusicGiftFor: 'Pentru ce este MusicGift?',
    marriageProposals: 'Cereri în căsătorie',
    seeExamples: 'Vezi exemple',
    chooseYourPackage: 'Alege Pachetul Tău',
    selectPerfectPackage: 'Selectează pachetul muzical perfect care se potrivește nevoilor și bugetului tău',
    failedToLoadPackages: 'Nu s-au putut încărca pachetele. Te rugăm să încerci din nou mai târziu.',
    reload: 'Reîncarcă',
    noPackagesAvailable: 'Nu sunt pachete disponibile momentan.',
    checkBackLater: 'Te rugăm să revii mai târziu.',
    viewAllPackages: 'Vezi Toate Pachetele',
    readyToCreateSpecial: 'Gata să Creezi Ceva Special?',
    helpCreatePersonalized: 'Lasă-ne să te ajutăm să creezi un cadou muzical personalizat care va fi prețuit pentru totdeauna.',
    startYourOrder: 'Începe Comanda',
    
    // Contact Page
    contactTitle: 'Contactează-ne',
    contactSubtitle: 'Ia legătura cu noi pentru orice întrebări sau pentru a-ți începe călătoria muzicală',
    getInTouch: 'Ia Legătura',
    contactDescription: 'Ne-ar face plăcere să auzim de la tine. Trimite-ne un mesaj și vom răspunde cât mai curând posibil.',
    emailUs: 'Trimite Email',
    callUs: 'Sună-ne',
    visitUs: 'Vizitează-ne',
    followUs: 'Urmărește-ne',
    sendMessage: 'Trimite Mesaj',
    yourName: 'Numele Tău',
    yourEmail: 'Emailul Tău',
    phoneNumber: 'Număr de Telefon',
    yourMessage: 'Mesajul Tău',
    sendMessageBtn: 'Trimite Mesaj',
    messageSent: 'Mesaj trimis!',
    messageThankYou: 'Mulțumim pentru mesaj. Îți vom răspunde în curând.',
    
    // Page Titles and Content
    howItWorksTitle: 'Cum Funcționează',
    howItWorksSubtitle: 'Urmează acești pași simpli pentru a-ți obține cântecul personalizat',
    aboutTitle: 'Despre Noi',
    aboutSubtitle: 'La MusicGift credem că muzica este cea mai pură formă de emoție.',
    aboutNewDescription1: 'În fiecare poveste personală există un cântec necântat, o emoție care merită să prindă viață. Transformăm aceste emoții în melodii reale, create de artiști reali, pentru oameni reali.',
    aboutNewDescription2: 'MusicGift s-a născut din dorința de a aduce oamenilor un cadou unic: un cântec creat special pentru ei. Într-o lume unde totul devine rapid și superficial, am ales să investim timp, suflet și pasiune în fiecare creație muzicală. Fondat de Mihai Gruia, producător muzical și fost membru al trupei internaționale Akcent, MusicGift combină experiența de scenă și studio cu emoția sinceră a poveștilor personale.',
    testimonialsTitle: 'Ce Spun Clienții Noștri',
    testimonialsSubtitle: 'Povești reale de la clienți mulțumiți care și-au transformat amintirile în muzică',
    packagesSubtitle: 'Selectează pachetul muzical perfect care se potrivește nevoilor și bugetului tău',
    
    // Testimonials Page
    testimonials_page_title: 'Testimoniale Clienți',
    testimonials_page_description: 'Descoperă ce spun clienții noștri despre experiența lor cu muzica personalizată',

    // Step Process
    choosePackage: 'Alege Pachetul',
    choosePackageDesc: 'Selectează din gama noastră de pachete muzicale personalizate',
    tellYourStory: 'Spune-ne Povestea',
    tellYourStoryDesc: 'Împărtășește detaliile și emoțiile pe care vrei să le surprindem',
    weCreate: 'Noi Creăm',
    weCreateDesc: 'Echipa noastră compune piesa ta muzicală unică',
    deliverDelight: 'Livrăm & Încântăm',
    deliverDelightDesc: 'Primește cântecul tău personalizat și păstrează-l pentru totdeauna',
    
    // Team
    ourTeam: 'Echipa Noastră',
    leadComposer: 'Compozitor Principal',
    leadVocalist: 'Vocalist Principal',
    soundEngineer: 'Inginer de Sunet',
    songsCreated: 'Cântece Create',
    yearsExperience: 'Ani de Experiență',
    clientSatisfaction: 'Satisfacția Clienților',
    
    // Testimonials
    testimonial1: 'Să lucrez cu MusicGift a fost minunat. Au înțeles perfect povestea noastră și au creat ceva magic!',
    author1: 'Maria & Alex',
    location1: 'București, România',
    testimonial2: 'Cântecul personalizat pentru aniversarea noastră a depășit așteptările. Perfecțiune pură!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, România',
    testimonial3: 'Cântecul de nuntă ne dă fiori de fiecare dată când îl auzim. Mulțumim pentru acest cadou frumos!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, România',
    
    // 404 Page
    pageNotFound: 'Pagină Negăsită',
    pageNotFoundDesc: 'Pagina pe care o cauți nu există',
    returnHome: 'Înapoi Acasă',
    
    // Order Page
    placeOrder: 'Plasează Comanda',
    orderSubtitle: 'Să creăm ceva magic împreună. Completează formularul de mai jos pentru a începe.',
    orderSent: 'Comandă trimisă!',
    orderThankYou: 'Mulțumim pentru comandă. Vă vom contacta în curând pentru confirmarea detaliilor.',
    orderError: 'Eroare',
    orderErrorMessage: 'A apărut o eroare la salvarea comenzii. Încercați din nou.',
    
    // Order Form Navigation
    backToHome: 'Înapoi Acasă',
    progress: 'Progres',
    previous: 'ANTERIOR',
    continue: 'CONTINUĂ',
    completeOrder: 'FINALIZEAZĂ COMANDA',
    submitting: 'SE TRIMITE...',
    of: 'din',
    
    // Order Form Validation
    completeRequiredFields: 'Te rugăm să completezi toate câmpurile obligatorii',
    completeRequiredFieldsDesc: 'Asigură-te că completezi toate informațiile necesare înainte de a continua.',
    orderSubmittedSuccess: 'Comanda a fost trimisă cu succes!',
    orderSubmittedDesc: 'Mulțumim pentru comandă. Te vom contacta în curând cu următorii pași.',
    somethingWentWrong: 'Ceva nu a mers bine',
    tryAgainSupport: 'Te rugăm să încerci din nou sau să contactezi suportul dacă problema persistă.',
    
    // Step Titles
    stepPackage: 'Pachet',
    stepDetails: 'Detalii',
    stepStory: 'Poveste',
    stepPreferences: 'Preferințe',
    stepContact: 'Contact',
    
    // Step Configuration
    generalDetails: 'Detalii generale',
    storyAndEmotionalDetails: 'Poveste și detalii emoționale',
    musicalPreferences: 'Preferințe muzicale',
    confirmation: 'Confirmare',
    
    // Package Details
    whatsIncluded: 'Ce include:',
    professionalQuality: 'Calitate profesională garantată',
    professionalQualityGuaranteed: 'Calitate Profesională Garantată',
    tellUsAboutRecipient: 'Spune-ne despre destinatar',
    helpUnderstand: 'Ajută-ne să înțelegem pentru cine este această melodie specială și ce ocazie sărbătorim.',
    
    // Order Summary
    orderSummary: 'Sumar Comandă',
    package: 'Pachet',
    delivery: 'Livrare',
    selectedAddons: 'Extra-uri Selectate',
    total: 'Total',
    
    // Help Section
    needHelp: 'Ai nevoie de ajutor?',
    mondayToFriday: 'Lun-Vin: 9:00-18:00',
    
    // Testimonial Section
    testimonialQuote: '"Să lucrez cu MusicGift a fost minunat. Au înțeles perfect povestea noastră și au creat ceva magic!"',
    testimonialAuthor: '— Radu & Elena',
    
    // Footer
    footerDescription: 'Creăm cadouri muzicale personalizate. Transformă momentele tale speciale în cântece frumoase și personalizate.',
    quickLinks: 'Linkuri Rapide',
    contactInfo: 'Informații Contact',
    legal: 'Legal',
    stayUpdated: 'Rămâi la Curent',
    newsletterDescription: 'Abonează-te pentru a primi oferte speciale, pachete noi și conținut muzical exclusiv direct în inbox.',
    enterEmail: 'Introdu adresa de email',
    subscribe: 'Abonează-te',
    subscribeDisclaimer: 'Prin abonare, ești de acord cu Politica de Confidențialitate și consimți să primești actualizări de la compania noastră.',
    copyright: '© 2025 MusicGift.ro. Toate drepturile rezervate. Făcut de RED DOMAIN cu ❤️ pentru iubitorii de muzică.',
    termsConditions: 'Termeni și Condiții',
    privacyPolicy: 'Politica de Confidențialitate',
    refundPolicy: 'Politica de Rambursare',
    cookiePolicy: 'Politica Cookie-urilor',
    admin: 'Admin',
    
    // Packages
    personalPackage: 'Pachet Personal',
    businessPackage: 'Pachet Business',
    premiumPackage: 'Pachet Premium',
    artistPackage: 'Pachet Artist',
    instrumentalPackage: 'Pachet Instrumental',
    remixPackage: 'Pachet Remix',
    giftPackage: 'Pachet Cadou',
    
    // Package Descriptions
    personalPackageDesc: 'Un cântec scris cu suflet – doar pentru tine și cei dragi.',
    personalPackageTagline: 'Ideal pentru aniversări, nunți sau ocazii speciale – transformăm povestea ta într-un cadou muzical unic și emoționant.',
    businessPackageDesc: 'Melodii comerciale profesionale pentru branduri și companii.',
    businessPackageTagline: 'Perfect pentru campanii publicitare, imnuri de brand sau evenimente corporative.',
    premiumPackageDesc: 'Melodie premium cu producție avansată și distribuție.',
    premiumPackageTagline: 'Distribuție profesională pe toate platformele cu suport promoțional.',
    artistPackageDesc: 'Colaborare artistică completă pentru muzicienii aspiranți.',
    artistPackageTagline: 'Producție muzicală completă cu videoclip profesional și marketing.',
    instrumentalPackageDesc: 'Muzică instrumentală personalizată în genul dorit.',
    instrumentalPackageTagline: 'Perfect pentru creatorii de conținut, podcasturi sau muzică de fundal.',
    remixPackageDesc: 'Remix profesional al piesei tale existente.',
    remixPackageTagline: 'Transformă-ți piesa cu tehnici moderne de producție.',
    giftPackageDesc: 'Cadou muzical personalizat cu prezentare frumoasă.',
    giftPackageTagline: 'Surpriza perfectă pentru cei dragi cu livrare elegantă.',
    
    // Languages
    romanian: 'Română',
    english: 'English',
    french: 'Français',
    german: 'Deutsch',
    polish: 'Polski',

    // Who We Are Section
    whoWeAre: 'Cine Suntem',
    mihaiGruiaTitle: 'Mihai Gruia',
    mihaiGruiaDescription: 'Producător muzical și compozitor, membru fondator al trupei Akcent – una dintre cele mai de succes trupe pop românești la nivel internațional, cu hituri celebre precum \'That\'s My Name\', \'Kylie\' și \'Stay with Me\'. După succesul Akcent, Mihai a continuat sa cariera artistică prin proiectul TWO și s-a implicat în producția muzicală pentru artiști de top. Astăzi, coordonează echipa MusicGift și DOMG Studio, aducându-și expertiza în fiecare proiect livrat.',
    mangoRecordsTitle: 'Mango Records',
    mangoRecordsDescription: 'Mango Records, fondat și coordonat de Mihai Gruia, este o casă de discuri independentă din România, specializată în lansarea și distribuirea muzicii originale internațional. A promovat artiști de succes precum TWO (ex-Akcent), DOMG, Mellina, Red Blonde, Pitt Leffer, Katerina și Vulgaris. Cu peste 1000 de piese distribuite global pe Spotify, Apple Music și YouTube, Mango Records contribuie activ la scena muzicală contemporană. A realizat și colaborări comerciale de succes cu branduri internaționale.',
    domgStudioTitle: 'DOMG Studio',
    domgStudioDescription: 'Studio premium de creație muzicală, cu compoziții pentru artiști de top români și internaționali: Akcent, Andra, Lora, Alina Eremia și alții. Oferă calitate audio impecabilă și procese profesionale de compoziție, înregistrare și mix-master.',
    doMusicForGoodTitle: 'Do Music for Good Band',
    doMusicForGoodDescription: 'O echipă de interpreți profesioniști care colaborează pentru a da viață melodiilor MusicGift. Fiecare voce și fiecare notă sunt alese cu grijă pentru a exprima autentic emoția transmisă de client.',
  },
  fr: {
    // Navigation
    home: 'Accueil',
    about: 'À Propos',
    packages: 'Forfaits',
    howItWorks: 'Comment Ça Marche',
    testimonials: 'Témoignages',
    contact: 'Contact',
    orderNow: 'Commander',
    signIn: 'Se connecter',
    user: 'Utilisateur',
    accountSettings: 'Paramètres du compte',
    signOut: 'Se déconnecter',
    selectYourPackage: 'Sélectionnez Votre Forfait',
    loadingPackages: 'Chargement des forfaits...',
    mostPopular: 'Le Plus Populaire',
    howItWorksTitle: 'Comment Ça Marche',
    howItWorksSubtitle: 'Suivez ces étapes simples pour obtenir votre chanson personnalisée',
    aboutTitle: 'À Propos de Nous',
    aboutSubtitle: 'Chez MusicGift, nous croyons que la musique est la forme la plus pure d\'émotion.',
    aboutNewDescription1: 'Dans chaque histoire personnelle, il y a une chanson non chantée, une émotion qui mérite de prendre vie. Nous transformons ces émotions en vraies mélodies, créées par de vrais artistes, pour de vraies personnes.',
    aboutNewDescription2: 'MusicGift est né du désir d\'apporter aux gens un cadeau unique : une chanson créée spécialement pour eux. Dans un monde où tout devient rapide et superficiel, nous avons choisi d\'investir du temps, de l\'âme et de la passion dans chaque création musicale. Fondé par Mihai Gruia, producteur de musique et ancien membre du groupe international Akcent, MusicGift combine l\'expérience de la scène et du studio avec l\'émotion sincère des histoires personnelles.',
    testimonialsTitle: 'Ce Que Disent Nos Clients',
    testimonialsSubtitle: 'Vraies histoires de clients satisfaits qui ont transformé leurs souvenirs en musique',
    packagesSubtitle: 'Sélectionnez le forfait musical parfait qui correspond à vos besoins et budget',
    choosePackage: 'Choisissez Votre Forfait',
    choosePackageDesc: 'Sélectionnez parmi notre gamme de forfaits musicaux personnalisés',
    tellYourStory: 'Racontez Votre Histoire',
    tellYourStoryDesc: 'Partagez les détails et émotions que vous voulez capturer',
    weCreate: 'Nous Créons',
    weCreateDesc: 'Notre équipe compose votre pièce musicale unique',
    deliverDelight: 'Livrer & Enchanter',
    deliverDelightDesc: 'Recevez votre chanson personnalisée et chérissez pour toujours',
    ourTeam: 'Notre Équipe',
    leadComposer: 'Compositeur Principal',
    leadVocalist: 'Vocaliste Principal',
    soundEngineer: 'Ingénieur du Son',
    songsCreated: 'Chansons Créées',
    yearsExperience: 'Années d\'Expérience',
    clientSatisfaction: 'Satisfaction Client',
    testimonial1: 'Travailler avec MusicGift était incroyable. Ils ont parfaitement compris notre histoire et ont créé quelque chose de magique!',
    author1: 'Maria & Alex',
    location1: 'Bucarest, Roumanie',
    testimonial2: 'La chanson personnalisée pour notre anniversaire a dépassé nos attentes. Pure perfection!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Roumanie',
    testimonial3: 'Notre chanson de mariage nous donne encore des frissons à chaque fois que nous l\'entendons. Merci pour ce beau cadeau!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Roumanie',
    pageNotFound: 'Page Non Trouvée',
    pageNotFoundDesc: 'La page que vous recherchez n\'existe pas',
    returnHome: 'Retour à l\'Accueil',
    whatsIncluded: 'Ce qui est inclus:',
    placeOrder: 'Passer Commande',
    orderSubtitle: 'Créons quelque chose de magique ensemble. Remplissez le formulaire ci-dessous pour commencer.',
    orderSent: 'Commande envoyée!',
    orderThankYou: 'Merci pour votre commande. Nous vous contacterons bientôt pour confirmer les détails.',
    orderError: 'Erreur',
    orderErrorMessage: 'Une erreur s\'est produite lors de l\'enregistrement de la commande. Veuillez réessayer.',
    backToHome: 'Retour à l\'accueil',
    progress: 'Progrès',
    previous: 'PRÉCÉDENT',
    continue: 'CONTINUER',
    completeOrder: 'FINALISER LA COMMANDE',
    submitting: 'ENVOI EN COURS...',
    of: 'de',
    stepPackage: 'Forfait',
    stepDetails: 'Détails',
    stepStory: 'Histoire',
    stepPreferences: 'Préférences',
    stepContact: 'Contact',
    personalPackage: 'Forfait Personnel',
    businessPackage: 'Forfait Entreprise',
    premiumPackage: 'Forfait Premium',
    artistPackage: 'Forfait Artiste',
    instrumentalPackage: 'Forfait Instrumental',
    remixPackage: 'Forfait Remix',
    giftPackage: 'Forfait Cadeau',
    required: '*',
    completeRequiredFields: 'Veuillez remplir tous les champs obligatoires',
    completeRequiredFieldsDesc: 'Assurez-vous de remplir toutes les informations nécessaires avant de continuer.',
    orderSubmittedSuccess: 'Commande soumise avec succès!',
    orderSubmittedDesc: 'Merci pour votre commande. Nous vous contactons bientôt avec les prochaines étapes.',
    somethingWentWrong: 'Quelque chose s\'est mal passé',
    tryAgainSupport: 'Veuillez réessayer ou contacter le support si le problème persiste.',
    generalDetails: 'Détails généraux',
    storyAndEmotionalDetails: 'Histoire et détails émotionnels',
    musicalPreferences: 'Préférences musicales',
    confirmation: 'Confirmation',
    professionalQuality: 'Qualité professionnelle garantie',
    professionalQualityGuaranteed: 'Qualité Professionnelle Garantie',
    tellUsAboutRecipient: 'Parlez-nous du destinataire',
    helpUnderstand: 'Aidez-nous à comprendre pour qui est cette chanson spéciale et quelle occasion nous célébrons.',
    orderSummary: 'Résumé de Commande',
    package: 'Forfait',
    delivery: 'Livraison',
    selectedAddons: 'Options Sélectionnées',
    total: 'Total',
    needHelp: 'Besoin d\'aide?',
    mondayToFriday: 'Lun-Ven: 9h-18h',
    testimonials_page_title: 'Témoignages Clients',
    testimonials_page_description: 'Découvrez ce que nos clients disent de leur expérience musicale personnalisée',
    testimonialQuote: '"Travailler avec MusicGift était incroyable. Ils ont parfaitement compris notre histoire et ont créé quelque chose de magique!"',
    testimonialAuthor: '— Radu & Elena',
    personalPackageDesc: 'Une chanson écrite avec âme – juste pour vous et vos proches.',
    personalPackageTagline: 'Idéal pour les anniversaires, mariages ou occasions spéciales.',
    businessPackageDesc: 'Chansons commerciales professionnelles pour marques et entreprises.',
    businessPackageTagline: 'Parfait pour les campagnes publicitaires ou événements corporatifs.',
    premiumPackageDesc: 'Chanson premium avec production avancée et distribution.',
    premiumPackageTagline: 'Distribution professionnelle sur toutes les plateformes.',
    artistPackageDesc: 'Collaboration artistique complète pour musiciens aspirants.',
    artistPackageTagline: 'Production musicale complète avec vidéo et marketing professionnels.',
    instrumentalPackageDesc: 'Musique instrumentale personnalisée dans le genre désiré.',
    instrumentalPackageTagline: 'Parfait pour créateurs de contenu ou musique de fond.',
    remixPackageDesc: 'Remix professionnel de votre chanson existante.',
    remixPackageTagline: 'Transformez votre chanson avec des techniques modernes.',
    giftPackageDesc: 'Cadeau musical personnalisé avec belle présentation.',
    giftPackageTagline: 'La surprise parfaite avec livraison élégante.',
    romanian: 'Roumain',
    english: 'Anglais',
    french: 'Français',
    german: 'Allemand',
    polish: 'Polonais',
    heroTitle: 'Offrez le Cadeau de la Musique',
    heroSubtitle: 'Une chanson personnalisée, créée spécialement pour votre être cher. Le cadeau le plus unique qu\'ils recevront jamais.',
    seePackages: 'Voir les Forfaits',
    listenToSamples: 'Écouter les Échantillons',
    whatIsMusicGiftFor: 'À quoi sert MusicGift?',
    marriageProposals: 'Demandes en mariage',
    seeExamples: 'Voir les exemples',
    chooseYourPackage: 'Choisissez Votre Forfait',
    selectPerfectPackage: 'Sélectionnez le forfait musical parfait qui correspond à vos besoins et budget',
    failedToLoadPackages: 'Échec du chargement des forfaits. Veuillez réessayer plus tard.',
    reload: 'Recharger',
    noPackagesAvailable: 'Aucun forfait disponible pour le moment.',
    checkBackLater: 'Veuillez revenir plus tard.',
    viewAllPackages: 'Voir Tous les Forfaits',
    readyToCreateSpecial: 'Prêt à Créer Quelque Chose de Spécial?',
    helpCreatePersonalized: 'Laissez-nous vous aider à créer un cadeau musical personnalisé qui sera chéri pour toujours.',
    startYourOrder: 'Commencer Votre Commande',
    contactTitle: 'Contactez-nous',
    contactSubtitle: 'Contactez-nous pour toute question ou pour commencer votre voyage musical',
    getInTouch: 'Entrer en Contact',
    contactDescription: 'Nous aimerions avoir de vos nouvelles. Envoyez-nous un message et nous répondrons dès que possible.',
    emailUs: 'Envoyez-nous un Email',
    callUs: 'Appelez-nous',
    visitUs: 'Visitez-nous',
    followUs: 'Suivez-nous',
    sendMessage: 'Envoyer un Message',
    yourName: 'Votre Nom',
    yourEmail: 'Votre Email',
    phoneNumber: 'Numéro de Téléphone',
    yourMessage: 'Votre Message',
    sendMessageBtn: 'Envoyer le Message',
    messageSent: 'Message envoyé!',
    messageThankYou: 'Merci pour votre message. Nous vous répondrons bientôt.',
    footerDescription: 'Créer des cadeaux musicaux personnalisés. Transformez vos moments spéciaux en belles chansons personnalisées.',
    quickLinks: 'Liens Rapides',
    contactInfo: 'Informations de Contact',
    legal: 'Légal',
    stayUpdated: 'Restez Informé',
    newsletterDescription: 'Abonnez-vous pour recevoir des offres spéciales, de nouveaux forfaits et du contenu musical exclusif directement dans votre boîte de réception.',
    enterEmail: 'Entrez votre adresse email',
    subscribe: 'S\'abonner',
    subscribeDisclaimer: 'En vous abonnant, vous acceptez notre Politique de Confidentialité et consentez à recevoir des mises à jour de notre entreprise.',
    copyright: '© 2025 MusicGift.ro. Tous droits réservés. Fait par RED DOMAIN avec ❤️ pour les amateurs de musique.',
    termsConditions: 'Termes et Conditions',
    privacyPolicy: 'Politique de Confidentialité',
    refundPolicy: 'Politique de Remboursement',
    cookiePolicy: 'Politique des Cookies',
    admin: 'Admin',
    selectLanguage: 'Sélectionner la langue',
    selectOption: 'Sélectionner une option',

    // Who We Are Section
    whoWeAre: 'Qui Nous Sommes',
    mihaiGruiaTitle: 'Mihai Gruia',
    mihaiGruiaDescription: 'Producteur de musique et compositeur, membre fondateur d\'Akcent – l\'un des groupes pop roumains les plus réussis internationalement, avec des hits célèbres comme \'That\'s My Name\', \'Kylie\' et \'Stay with Me\'. Après le succès d\'Akcent, Mihai a continué sa carrière artistique à travers le projet TWO et s\'est impliqué dans la production musicale pour des artistes de premier plan. Aujourd\'hui, il coordonne l\'équipe MusicGift et DOMG Studio, apportant son expertise à chaque projet livré.',
    mangoRecordsTitle: 'Mango Records',
    mangoRecordsDescription: 'Mango Records, fondé et coordonné par Mihai Gruia, est un label indépendant de Roumanie, spécialisé dans le lancement et la distribution de musique originale internationalement. Il a promu des artistes à succès comme TWO (ex-Akcent), DOMG, Mellina, Red Blonde, Pitt Leffer, Katerina et Vulgaris. Avec plus de 1000 morceaux distribués mondialement sur Spotify, Apple Music et YouTube, Mango Records contribue activement à la scène musicale contemporaine. Il a également réalisé des collaborations commerciales réussies avec des marques internationales.',
    domgStudioTitle: 'DOMG Studio',
    domgStudioDescription: 'Studio de création musicale premium, avec des compositions pour des artistes roumains et internationaux de premier plan : Akcent, Andra, Lora, Alina Eremia et autres. Offre une qualité audio impeccable et des processus professionnels de composition, d\'enregistrement et de mix-master.',
    doMusicForGoodTitle: 'Do Music for Good Band',
    doMusicForGoodDescription: 'Une équipe d\'interprètes professionnels qui collaborent pour donner vie aux mélodies MusicGift. Chaque voix et chaque note sont soigneusement choisies pour exprimer authentiquement l\'émotion transmise par le client.',
  },
  pl: {
    // Navigation
    home: 'Strona Główna',
    about: 'O Nas',
    packages: 'Pakiety',
    howItWorks: 'Jak To Działa',
    testimonials: 'Opinie',
    contact: 'Kontakt',
    orderNow: 'Zamów Teraz',
    signIn: 'Zaloguj się',
    user: 'Użytkownik',
    accountSettings: 'Ustawienia konta',
    signOut: 'Wyloguj się',
    selectYourPackage: 'Wybierz Swój Pakiet',
    loadingPackages: 'Ładowanie pakietów...',
    mostPopular: 'Najpopularniejszy',
    howItWorksTitle: 'Jak To Działa',
    howItWorksSubtitle: 'Wykonaj te proste kroki, aby otrzymać swoją spersonalizowaną piosenkę',
    aboutTitle: 'O Nas',
    aboutSubtitle: 'W MusicGift wierzymy, że muzyka to najczystsza forma emocji.',
    aboutNewDescription1: 'W każdej osobistej historii jest niezaśpiewana piosenka, emocja, która zasługuje na to, aby ożyć. Przekształcamy te emocje w prawdziwe melodie, tworzone przez prawdziwych artystów, dla prawdziwych ludzi.',
    aboutNewDescription2: 'MusicGift powstał z chęci przyniesienia ludziom unikalnego prezentu: piosenki stworzonej specjalnie dla nich. W świecie, gdzie wszystko staje się szybkie i powierzchowne, wybraliśmy inwestowanie czasu, duszy i pasji w każdą muzyczną kreację. Założone przez Mihai Gruia, producenta muzycznego i byłego członka międzynarodowej grupy Akcent, MusicGift łączy doświadczenie sceniczne i studyjne z szczerą emocją osobistych historii.',
    testimonialsTitle: 'Co Mówią Nasi Klienci',
    testimonialsSubtitle: 'Prawdziwe historie od zadowolonych klientów, którzy zamienili swoje wspomnienia w muzykę',
    packagesSubtitle: 'Wybierz idealny pakiet muzyczny, który pasuje do Twoich potrzeb i budżetu',
    choosePackage: 'Wybierz Swój Pakiet',
    choosePackageDesc: 'Wybierz z naszej gamy spersonalizowanych pakietów muzycznych',
    tellYourStory: 'Opowiedz Swoją Historię',
    tellYourStoryDesc: 'Podziel się szczegółami i emocjami, które chcesz uchwycić',
    weCreate: 'Tworzymy',
    weCreateDesc: 'Nasz zespół komponuje Twój unikalny utwór muzyczny',
    deliverDelight: 'Dostarczamy i Zachwycamy',
    deliverDelightDesc: 'Otrzymaj swoją spersonalizowaną piosenkę i ciesz się nią na zawsze',
    ourTeam: 'Nasz Zespół',
    leadComposer: 'Główny Kompozytor',
    leadVocalist: 'Główny Wokalista',
    soundEngineer: 'Inżynier Dźwięku',
    songsCreated: 'Utworzone Piosenki',
    yearsExperience: 'Lata Doświadczenia',
    clientSatisfaction: 'Zadowolenie Klientów',
    testimonial1: 'Praca z MusicGift była niesamowita. Doskonale zrozumieli naszą historię i stworzyli coś magicznego!',
    author1: 'Maria & Alex',
    location1: 'Bukareszt, Rumunia',
    testimonial2: 'Spersonalizowana piosenka na naszą rocznicę przewyższyła nasze oczekiwania. Czysta perfekcja!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Rumunia',
    testimonial3: 'Nasza piosenka ślubna wciąż daje nam dreszcze za każdym razem, gdy ją słyszymy. Dziękujemy za ten piękny prezent!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Rumunia',
    pageNotFound: 'Strona Nie Znaleziona',
    pageNotFoundDesc: 'Strona, której szukasz, nie istnieje',
    returnHome: 'Powrót do Domu',
    whatsIncluded: 'Co jest zawarte:',
    placeOrder: 'Złóż Zamówienie',
    orderSubtitle: 'Stwórzmy razem coś magicznego. Wypełnij formularz poniżej, aby rozpocząć.',
    orderSent: 'Zamówienie wysłane!',
    orderThankYou: 'Dziękujemy za zamówienie. Skontaktujemy się z Tobą wkrótce, aby potwierdzić szczegóły.',
    orderError: 'Błąd',
    orderErrorMessage: 'Wystąpił błąd podczas zapisywania zamówienia. Spróbuj ponownie.',
    backToHome: 'Powrót do domu',
    progress: 'Postęp',
    previous: 'POPRZEDNI',
    continue: 'KONTYNUUJ',
    completeOrder: 'ZAKOŃCZ ZAMÓWIENIE',
    submitting: 'WYSYŁANIE...',
    of: 'z',
    stepPackage: 'Pakiet',
    stepDetails: 'Szczegóły',
    stepStory: 'Historia',
    stepPreferences: 'Preferencje',
    stepContact: 'Kontakt',
    personalPackage: 'Pakiet Osobisty',
    businessPackage: 'Pakiet Biznesowy',
    premiumPackage: 'Pakiet Premium',
    artistPackage: 'Pakiet Artysty',
    instrumentalPackage: 'Pakiet Instrumentalny',
    remixPackage: 'Pakiet Remix',
    giftPackage: 'Pakiet Prezentowy',
    required: '*',
    completeRequiredFields: 'Proszę wypełnić wszystkie wymagane pola',
    completeRequiredFieldsDesc: 'Upewnij się, że wypełniłeś wszystkie niezbędne informacje przed kontynuowaniem.',
    orderSubmittedSuccess: 'Zamówienie zostało złożone pomyślnie!',
    orderSubmittedDesc: 'Dziękujemy za zamówienie. Skontaktujemy się z Tobą wkrótce z następnymi krokami.',
    somethingWentWrong: 'Coś poszło nie tak',
    tryAgainSupport: 'Spróbuj ponownie lub skontaktuj się z pomocą techniczną, jeśli problem będzie się powtarzał.',
    generalDetails: 'Szczegóły ogólne',
    storyAndEmotionalDetails: 'Historia i szczegóły emocjonalne',
    musicalPreferences: 'Preferencje muzyczne',
    confirmation: 'Potwierdzenie',
    professionalQuality: 'Gwarantowana jakość profesjonalna',
    professionalQualityGuaranteed: 'Gwarantowana Jakość Profesjonalna',
    tellUsAboutRecipient: 'Opowiedz nam o odbiorcy',
    helpUnderstand: 'Pomóż nam zrozumieć, dla kogo jest ta specjalna piosenka i jaką okazję świętujemy.',
    orderSummary: 'Podsumowanie Zamówienia',
    package: 'Pakiet',
    delivery: 'Dostawa',
    selectedAddons: 'Wybrane Dodatki',
    total: 'Razem',
    needHelp: 'Potrzebujesz pomocy?',
    mondayToFriday: 'Pon-Pt: 9:00-18:00',
    testimonials_page_title: 'Opinie Klientów',
    testimonials_page_description: 'Odkryj, co nasi klienci mówią o swoim spersonalizowanym doświadczeniu muzycznym',
    testimonialQuote: '"Praca z MusicGift była niesamowita. Doskonale zrozumieli naszą historię i stworzyli coś magicznego!"',
    testimonialAuthor: '— Radu & Elena',
    personalPackageDesc: 'Piosenka napisana z duszą – tylko dla Ciebie i Twoich bliskich.',
    personalPackageTagline: 'Idealna na urodziny, wesela lub specjalne okazje.',
    businessPackageDesc: 'Profesjonalne piosenki komercyjne dla marek i firm.',
    businessPackageTagline: 'Idealne do kampanii reklamowych lub wydarzeń korporacyjnych.',
    premiumPackageDesc: 'Piosenka premium z zaawansowaną produkcją i dystrybucją.',
    premiumPackageTagline: 'Profesjonalna dystrybucja na wszystkich platformach.',
    artistPackageDesc: 'Pełna współpraca artystyczna dla aspirujących muzyków.',
    artistPackageTagline: 'Kompletna produkcja muzyczna z profesjonalnym wideo i marketingiem.',
    instrumentalPackageDesc: 'Spersonalizowana muzyka instrumentalna w pożądanym gatunku.',
    instrumentalPackageTagline: 'Idealna dla twórców treści lub muzyki tła.',
    remixPackageDesc: 'Profesjonalny remix Twojej istniejącej piosenki.',
    remixPackageTagline: 'Przekształć swoją piosenkę nowoczesnymi technikami.',
    giftPackageDesc: 'Spersonalizowany prezent muzyczny z piękną prezentacją.',
    giftPackageTagline: 'Idealna niespodzianka z elegancką dostawą.',
    romanian: 'Rumuński',
    english: 'Angielski',
    french: 'Francuski',
    german: 'Niemiecki',
    polish: 'Polski',
    heroTitle: 'Daj Prezent Muzyki',
    heroSubtitle: 'Spersonalizowana piosenka, stworzona specjalnie dla Twojej wyjątkowej osoby. Najbardziej unikalny prezent, jaki kiedykolwiek otrzymają.',
    seePackages: 'Zobacz Pakiety',
    listenToSamples: 'Posłuchaj Próbek',
    whatIsMusicGiftFor: 'Do czego służy MusicGift?',
    marriageProposals: 'Oświadczyny',
    seeExamples: 'Zobacz przykłady',
    chooseYourPackage: 'Wybierz Swój Pakiet',
    selectPerfectPackage: 'Wybierz idealny pakiet muzyczny, który pasuje do Twoich potrzeb i budżetu',
    failedToLoadPackages: 'Nie udało się załadować pakietów. Spróbuj ponownie później.',
    reload: 'Przeładuj',
    noPackagesAvailable: 'Brak dostępnych pakietów w tej chwili.',
    checkBackLater: 'Sprawdź ponownie później.',
    viewAllPackages: 'Zobacz Wszystkie Pakiety',
    readyToCreateSpecial: 'Gotowy Stworzyć Coś Wyjątkowego?',
    helpCreatePersonalized: 'Pozwól nam pomóc Ci stworzyć spersonalizowany prezent muzyczny, który będzie ceniony na zawsze.',
    startYourOrder: 'Rozpocznij Zamówienie',
    contactTitle: 'Skontaktuj się z nami',
    contactSubtitle: 'Skontaktuj się z nami w przypadku pytań lub aby rozpocząć swoją muzyczną podróż',
    getInTouch: 'Skontaktuj się',
    contactDescription: 'Chcielibyśmy usłyszeć od Ciebie. Wyślij nam wiadomość, a odpowiemy tak szybko, jak to możliwe.',
    emailUs: 'Wyślij Email',
    callUs: 'Zadzwoń do nas',
    visitUs: 'Odwiedź nas',
    followUs: 'Śledź nas',
    sendMessage: 'Wyślij Wiadomość',
    yourName: 'Twoje Imię',
    yourEmail: 'Twój Email',
    phoneNumber: 'Numer Telefonu',
    yourMessage: 'Twoja Wiadomość',
    sendMessageBtn: 'Wyślij Wiadomość',
    messageSent: 'Wiadomość wysłana!',
    messageThankYou: 'Dziękujemy za wiadomość. Odpowiemy wkrótce.',
    footerDescription: 'Tworzenie spersonalizowanych prezentów muzycznych. Przekształć swoje specjalne chwile w piękne, personalizowane piosenki.',
    quickLinks: 'Szybkie Linki',
    contactInfo: 'Informacje Kontaktowe',
    legal: 'Prawne',
    stayUpdated: 'Bądź na Bieżąco',
    newsletterDescription: 'Subskrybuj, aby otrzymywać specjalne oferty, nowe pakiety i ekskluzywne treści muzyczne bezpośrednio do swojej skrzynki odbiorczej.',
    enterEmail: 'Wprowadź swój adres email',
    subscribe: 'Subskrybuj',
    subscribeDisclaimer: 'Subskrybując, wyrażasz zgodę na naszą Politykę Prywatności i zgadzasz się na otrzymywanie aktualizacji od naszej firmy.',
    copyright: '© 2025 MusicGift.ro. Wszystkie prawa zastrzeżone. Stworzone przez RED DOMAIN z ❤️ dla miłośników muzyki.',
    termsConditions: 'Warunki i Postanowienia',
    privacyPolicy: 'Polityka Prywatności',
    refundPolicy: 'Polityka Zwrotów',
    cookiePolicy: 'Polityka Cookies',
    admin: 'Admin',
    selectLanguage: 'Wybierz język',
    selectOption: 'Wybierz opcję',

    // Who We Are Section
    whoWeAre: 'Kim Jesteśmy',
    mihaiGruiaTitle: 'Mihai Gruia',
    mihaiGruiaDescription: 'Producent muzyczny i kompozytor, członek założyciel Akcent – jednego z najbardziej udanych rumuńskich zespołów popowych na arenie międzynarodowej, ze słynnymi hitami jak \'That\'s My Name\', \'Kylie\' i \'Stay with Me\'. Po sukcesie Akcent, Mihai kontynuował swoją karierę artystyczną przez projekt TWO i zaangażował się w produkcję muzyczną dla najlepszych artystów. Dziś koordynuje zespół MusicGift i DOMG Studio, wnosząc swoją wiedzę do każdego realizowanego projektu.',
    mangoRecordsTitle: 'Mango Records',
    mangoRecordsDescription: 'Mango Records, założone i koordynowane przez Mihai Gruia, to niezależna wytwórnia płytowa z Rumunii, specjalizująca się w lansowaniu i dystrybucji oryginalnej muzyki na arenie międzynarodowej. Promowała udanych artystów jak TWO (ex-Akcent), DOMG, Mellina, Red Blonde, Pitt Leffer, Katerina i Vulgaris. Z ponad 1000 utworów dystrybuowanych globalnie na Spotify, Apple Music i YouTube, Mango Records aktywnie przyczynia się do współczesnej sceny muzycznej. Osiągnęła również udane współprace komercyjne z międzynarodowymi markami.',
    domgStudioTitle: 'DOMG Studio',
    domgStudioDescription: 'Premium studio tworzenia muzyki, z kompozycjami dla najlepszych rumuńskich i międzynarodowych artystów: Akcent, Andra, Lora, Alina Eremia i innych. Oferuje nienaganną jakość dźwięku i profesjonalne procesy kompozycji, nagrywania i mix-master.',
    doMusicForGoodTitle: 'Do Music for Good Band',
    doMusicForGoodDescription: 'Zespół profesjonalnych wykonawców, którzy współpracują, aby ożywić melodie MusicGift. Każdy głos i każda nuta są starannie wybrane, aby autentycznie wyrazić emocję przekazaną przez klienta.',
  },
  de: {
    // Navigation
    home: 'Startseite',
    about: 'Über Uns',
    packages: 'Pakete',
    howItWorks: 'Wie Es Funktioniert',
    testimonials: 'Bewertungen',
    contact: 'Kontakt',
    orderNow: 'Jetzt Bestellen',
    signIn: 'Anmelden',
    user: 'Benutzer',
    accountSettings: 'Kontoeinstellungen',
    signOut: 'Abmelden',
    selectYourPackage: 'Wählen Sie Ihr Paket',
    loadingPackages: 'Pakete werden geladen...',
    mostPopular: 'Beliebtestes',
    howItWorksTitle: 'Wie Es Funktioniert',
    howItWorksSubtitle: 'Folgen Sie diesen einfachen Schritten, um Ihr personalisiertes Lied zu erhalten',
    aboutTitle: 'Über Uns',
    aboutSubtitle: 'Bei MusicGift glauben wir, dass Musik die reinste Form der Emotion ist.',
    aboutNewDescription1: 'In jeder persönlichen Geschichte gibt es ein ungesungenes Lied, eine Emotion, die es verdient, zum Leben erweckt zu werden. Wir verwandeln diese Emotionen in echte Melodien, geschaffen von echten Künstlern, für echte Menschen.',
    aboutNewDescription2: 'MusicGift entstand aus dem Wunsch, Menschen ein einzigartiges Geschenk zu bringen: ein Lied, das speziell für sie geschaffen wurde. In einer Welt, wo alles schnell und oberflächlich wird, haben wir uns entschieden, Zeit, Seele und Leidenschaft in jede musikalische Kreation zu investieren. Gegründet von Mihai Gruia, Musikproduzent und ehemaliges Mitglied der internationalen Band Akcent, kombiniert MusicGift Bühnen- und Studioerfahrung mit der aufrichtigen Emotion persönlicher Geschichten.',
    testimonialsTitle: 'Was Unsere Kunden Sagen',
    testimonialsSubtitle: 'Echte Geschichten von zufriedenen Kunden, die ihre Erinnerungen in Musik verwandelt haben',
    packagesSubtitle: 'Wählen Sie das perfekte Musikpaket, das zu Ihren Bedürfnissen und Ihrem Budget passt',
    choosePackage: 'Wählen Sie Ihr Paket',
    choosePackageDesc: 'Wählen Sie aus unserem Sortiment an personalisierten Musikpaketen',
    tellYourStory: 'Erzählen Sie Ihre Geschichte',
    tellYourStoryDesc: 'Teilen Sie die Details und Emotionen mit, die Sie einfangen möchten',
    weCreate: 'Wir Erschaffen',
    weCreateDesc: 'Unser Team komponiert Ihr einzigartiges Musikstück',
    deliverDelight: 'Liefern & Begeistern',
    deliverDelightDesc: 'Erhalten Sie Ihr personalisiertes Lied und schätzen Sie es für immer',
    ourTeam: 'Unser Team',
    leadComposer: 'Hauptkomponist',
    leadVocalist: 'Hauptsänger',
    soundEngineer: 'Toningenieur',
    songsCreated: 'Erstellte Lieder',
    yearsExperience: 'Jahre Erfahrung',
    clientSatisfaction: 'Kundenzufriedenheit',
    testimonial1: 'Mit MusicGift zu arbeiten war erstaunlich. Sie haben unsere Geschichte perfekt verstanden und etwas Magisches geschaffen!',
    author1: 'Maria & Alex',
    location1: 'Bukarest, Rumänien',
    testimonial2: 'Das personalisierte Lied für unseren Jahrestag übertraf unsere Erwartungen. Pure Perfektion!',
    author2: 'Carmen & Ion',
    location2: 'Cluj-Napoca, Rumänien',
    testimonial3: 'Unser Hochzeitslied gibt uns immer noch Gänsehaut, jedes Mal wenn wir es hören. Danke für dieses schöne Geschenk!',
    author3: 'Ana & Mihai',
    location3: 'Timișoara, Rumänien',
    pageNotFound: 'Seite Nicht Gefunden',
    pageNotFoundDesc: 'Die Seite, die Sie suchen, existiert nicht',
    returnHome: 'Zurück zur Startseite',
    whatsIncluded: 'Was ist enthalten:',
    placeOrder: 'Bestellung Aufgeben',
    orderSubtitle: 'Lassen Sie uns gemeinsam etwas Magisches schaffen. Füllen Sie das untenstehende Formular aus, um zu beginnen.',
    orderSent: 'Bestellung gesendet!',
    orderThankYou: 'Vielen Dank für Ihre Bestellung. Wir werden Sie bald kontaktieren, um die Details zu bestätigen.',
    orderError: 'Fehler',
    orderErrorMessage: 'Beim Speichern der Bestellung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    backToHome: 'Zurück zur Startseite',
    progress: 'Fortschritt',
    previous: 'ZURÜCK',
    continue: 'WEITER',
    completeOrder: 'BESTELLUNG ABSCHLIESSEN',
    submitting: 'WIRD GESENDET...',
    of: 'von',
    stepPackage: 'Paket',
    stepDetails: 'Details',
    stepStory: 'Geschichte',
    stepPreferences: 'Präferenzen',
    stepContact: 'Kontakt',
    personalPackage: 'Persönliches Paket',
    businessPackage: 'Business Paket',
    premiumPackage: 'Premium Paket',
    artistPackage: 'Künstler Paket',
    instrumentalPackage: 'Instrumental Paket',
    remixPackage: 'Remix Paket',
    giftPackage: 'Geschenk Paket',
    required: '*',
    completeRequiredFields: 'Bitte füllen Sie alle Pflichtfelder aus',
    completeRequiredFieldsDesc: 'Stellen Sie sicher, dass Sie alle erforderlichen Informationen eingeben, bevor Sie fortfahren.',
    orderSubmittedSuccess: 'Bestellung erfolgreich übermittelt!',
    orderSubmittedDesc: 'Vielen Dank für Ihre Bestellung. Wir werden Sie bald mit den nächsten Schritten kontaktieren.',
    somethingWentWrong: 'Etwas ist schiefgelaufen',
    tryAgainSupport: 'Bitte versuchen Sie es erneut oder kontaktieren Sie den Support, wenn das Problem weiterhin besteht.',
    generalDetails: 'Allgemeine Details',
    storyAndEmotionalDetails: 'Geschichte und emotionale Details',
    musicalPreferences: 'Musikalische Präferenzen',
    confirmation: 'Bestätigung',
    professionalQuality: 'Professionelle Qualität garantiert',
    professionalQualityGuaranteed: 'Professionelle Qualität Garantiert',
    tellUsAboutRecipient: 'Erzählen Sie uns über den Empfänger',
    helpUnderstand: 'Helfen Sie uns zu verstehen, für wen dieses besondere Lied ist und welchen Anlass wir feiern.',
    orderSummary: 'Bestellübersicht',
    package: 'Paket',
    delivery: 'Lieferung',
    selectedAddons: 'Ausgewählte Extras',
    total: 'Gesamt',
    needHelp: 'Brauchen Sie Hilfe?',
    mondayToFriday: 'Mo-Fr: 9:00-18:00',
    testimonials_page_title: 'Kundenbewertungen',
    testimonials_page_description: 'Entdecken Sie, was unsere Kunden über ihre personalisierte Musikerfahrung sagen',
    testimonialQuote: '"Mit MusicGift zu arbeiten war erstaunlich. Sie haben unsere Geschichte perfekt verstanden und etwas Magisches geschaffen!"',
    testimonialAuthor: '— Radu & Elena',
    personalPackageDesc: 'Ein Lied mit Seele geschrieben – nur für Sie und Ihre Lieben.',
    personalPackageTagline: 'Ideal für Geburtstage, Hochzeiten oder besondere Anlässe.',
    businessPackageDesc: 'Professionelle kommerzielle Lieder für Marken und Unternehmen.',
    businessPackageTagline: 'Perfekt für Werbekampagnen oder Unternehmensveranstaltungen.',
    premiumPackageDesc: 'Premium-Lied mit fortschrittlicher Produktion und Vertrieb.',
    premiumPackageTagline: 'Professioneller Vertrieb auf allen Plattformen.',
    artistPackageDesc: 'Vollständige künstlerische Zusammenarbeit für aufstrebende Musiker.',
    artistPackageTagline: 'Komplette Musikproduktion mit professionellem Video und Marketing.',
    instrumentalPackageDesc: 'Maßgeschneiderte Instrumentalmusik im gewünschten Genre.',
    instrumentalPackageTagline: 'Perfekt für Content-Ersteller oder Hintergrundmusik.',
    remixPackageDesc: 'Professioneller Remix Ihres bestehenden Liedes.',
    remixPackageTagline: 'Verwandeln Sie Ihr Lied mit modernen Produktionstechniken.',
    giftPackageDesc: 'Personalisiertes Musikgeschenk mit schöner Präsentation.',
    giftPackageTagline: 'Die perfekte Überraschung mit eleganter Lieferung.',
    romanian: 'Rumänisch',
    english: 'Englisch',
    french: 'Französisch',
    german: 'Deutsch',
    polish: 'Polnisch',
    heroTitle: 'Schenken Sie das Geschenk der Musik',
    heroSubtitle: 'Ein personalisiertes Lied, speziell für Ihre besondere Person erstellt. Das einzigartigste Geschenk, das sie jemals erhalten werden.',
    seePackages: 'Pakete Ansehen',
    listenToSamples: 'Hörproben Anhören',
    whatIsMusicGiftFor: 'Wofür ist MusicGift?',
    marriageProposals: 'Heiratsanträge',
    seeExamples: 'Beispiele ansehen',
    chooseYourPackage: 'Wählen Sie Ihr Paket',
    selectPerfectPackage: 'Wählen Sie das perfekte Musikpaket, das zu Ihren Bedürfnissen und Ihrem Budget passt',
    failedToLoadPackages: 'Pakete konnten nicht geladen werden. Bitte versuchen Sie es später erneut.',
    reload: 'Neu laden',
    noPackagesAvailable: 'Momentan sind keine Pakete verfügbar.',
    checkBackLater: 'Schauen Sie später noch einmal vorbei.',
    viewAllPackages: 'Alle Pakete Anzeigen',
    readyToCreateSpecial: 'Bereit, Etwas Besonderes zu Schaffen?',
    helpCreatePersonalized: 'Lassen Sie uns Ihnen helfen, ein personalisiertes Musikgeschenk zu erstellen, das für immer geschätzt wird.',
    startYourOrder: 'Bestellung Starten',
    contactTitle: 'Kontaktieren Sie uns',
    contactSubtitle: 'Setzen Sie sich mit uns in Verbindung für Fragen oder um Ihre musikalische Reise zu beginnen',
    getInTouch: 'Kontakt Aufnehmen',
    contactDescription: 'Wir würden gerne von Ihnen hören. Senden Sie uns eine Nachricht und wir werden so schnell wie möglich antworten.',
    emailUs: 'E-Mail senden',
    callUs: 'Anrufen',
    visitUs: 'Besuchen Sie uns',
    followUs: 'Folgen Sie uns',
    sendMessage: 'Nachricht Senden',
    yourName: 'Ihr Name',
    yourEmail: 'Ihre E-Mail',
    phoneNumber: 'Telefonnummer',
    yourMessage: 'Ihre Nachricht',
    sendMessageBtn: 'Nachricht Senden',
    messageSent: 'Nachricht gesendet!',
    messageThankYou: 'Vielen Dank für Ihre Nachricht. Wir werden uns bald bei Ihnen melden.',
    footerDescription: 'Personalisierte Musikgeschenke erstellen. Verwandeln Sie Ihre besonderen Momente in schöne, personalisierte Lieder.',
    quickLinks: 'Schnelle Links',
    contactInfo: 'Kontaktinformationen',
    legal: 'Rechtliches',
    stayUpdated: 'Bleiben Sie auf dem Laufenden',
    newsletterDescription: 'Abonnieren Sie, um spezielle Angebote, neue Pakete und exklusive Musikinhalte direkt in Ihren Posteingang zu erhalten.',
    enterEmail: 'Geben Sie Ihre E-Mail-Adresse ein',
    subscribe: 'Abonnieren',
    subscribeDisclaimer: 'Mit dem Abonnieren stimmen Sie unserer Datenschutzrichtlinie zu und erteilen die Einwilligung, Updates von unserem Unternehmen zu erhalten.',
    copyright: '© 2025 MusicGift.ro. Alle Rechte vorbehalten. Erstellt von RED DOMAIN mit ❤️ für Musikliebhaber.',
    termsConditions: 'Allgemeine Geschäftsbedingungen',
    privacyPolicy: 'Datenschutzrichtlinie',
    refundPolicy: 'Rückerstattungsrichtlinie',
    cookiePolicy: 'Cookie-Richtlinie',
    admin: 'Admin',
    selectLanguage: 'Sprache auswählen',
    selectOption: 'Option auswählen',

    // Who We Are Section
    whoWeAre: 'Wer Wir Sind',
    mihaiGruiaTitle: 'Mihai Gruia',
    mihaiGruiaDescription: 'Musikproduzent und Komponist, Gründungsmitglied von Akcent – einer der erfolgreichsten rumänischen Popbands international, mit berühmten Hits wie \'That\'s My Name\', \'Kylie\' und \'Stay with Me\'. Nach Akcents Erfolg setzte Mihai seine künstlerische Laufbahn durch das TWO-Projekt fort und engagierte sich in der Musikproduktion für Top-Künstler. Heute koordiniert er das MusicGift- und DOMG Studio-Team und bringt seine Expertise in jedes gelieferte Projekt ein.',
    mangoRecordsTitle: 'Mango Records',
    mangoRecordsDescription: 'Mango Records, gegründet und koordiniert von Mihai Gruia, ist ein unabhängiges Plattenlabel aus Rumänien, spezialisiert auf die internationale Veröffentlichung und Vertrieb von Originalmusik. Es hat erfolgreiche Künstler wie TWO (ex-Akcent), DOMG, Mellina, Red Blonde, Pitt Leffer, Katerina und Vulgaris gefördert. Mit über 1000 global auf Spotify, Apple Music und YouTube vertriebenen Tracks trägt Mango Records aktiv zur zeitgenössischen Musikszene bei. Es hat auch erfolgreiche kommerzielle Kooperationen mit internationalen Marken erreicht.',
    domgStudioTitle: 'DOMG Studio',
    domgStudioDescription: 'Premium-Musikstudio mit Kompositionen für top rumänische und internationale Künstler: Akcent, Andra, Lora, Alina Eremia und andere. Bietet tadellose Audioqualität und professionelle Kompositions-, Aufnahme- und Mix-Master-Prozesse.',
    doMusicForGoodTitle: 'Do Music for Good Band',
    doMusicForGoodDescription: 'Ein Team professioneller Interpreten, die zusammenarbeiten, um MusicGift-Melodien zum Leben zu erwecken. Jede Stimme und jede Note werden sorgfältig ausgewählt, um die vom Kunden übermittelte Emotion authentisch auszudrücken.',
  }
};

const languageNames = {
  en: 'EN',
  ro: 'RO',
  fr: 'FR',
  pl: 'PL',
  de: 'DE'
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('ro');

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languageNames };
