import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useDiscountCodes } from "@/hooks/useDiscountCodes";
import { TrendingUp, TrendingDown, Users, CreditCard, Gift, Target } from "lucide-react";

const DiscountCodeAnalytics = () => {
  const { data: codes, isLoading } = useDiscountCodes();

  if (isLoading) {
    return <div>Loading analytics...</div>;
  }

  const totalCodes = codes?.length || 0;
  const activeCodes = codes?.filter(code => code.is_active)?.length || 0;
  const expiredCodes = codes?.filter(code => code.expires_at && new Date(code.expires_at) < new Date())?.length || 0;
  const totalUsage = codes?.reduce((sum, code) => sum + code.used_count, 0) || 0;
  const autoGeneratedCodes = codes?.filter(code => code.code.includes('AUTO') || code.code.includes('RETURN') || code.code.includes('THANK'))?.length || 0;
  
  const topCodes = codes
    ?.filter(code => code.used_count > 0)
    ?.sort((a, b) => b.used_count - a.used_count)
    ?.slice(0, 5) || [];

  const stats = [
    {
      title: "Total Codes",
      value: totalCodes,
      icon: Gift,
      color: "text-blue-600",
      bgColor: "bg-blue-100",
    },
    {
      title: "Active Codes",
      value: activeCodes,
      icon: Target,
      color: "text-green-600",
      bgColor: "bg-green-100",
    },
    {
      title: "Auto-Generated",
      value: autoGeneratedCodes,
      icon: TrendingUp,
      color: "text-purple-600",
      bgColor: "bg-purple-100",
    },
    {
      title: "Total Usage",
      value: totalUsage,
      icon: Users,
      color: "text-orange-600",
      bgColor: "bg-orange-100",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Overview Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat, index) => {
          const Icon = stat.icon;
          return (
            <Card key={index}>
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">
                      {stat.title}
                    </p>
                    <p className="text-2xl font-bold">{stat.value}</p>
                  </div>
                  <div className={`p-2 rounded-lg ${stat.bgColor}`}>
                    <Icon className={`h-5 w-5 ${stat.color}`} />
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Top Performing Codes */}
        <Card>
          <CardHeader>
            <CardTitle>Top Performing Codes</CardTitle>
            <CardDescription>
              Discount codes with the highest usage
            </CardDescription>
          </CardHeader>
          <CardContent>
            {topCodes.length === 0 ? (
              <p className="text-muted-foreground text-center py-4">
                No codes have been used yet.
              </p>
            ) : (
              <div className="space-y-4">
                {topCodes.map((code, index) => (
                  <div key={code.id} className="flex items-center justify-between p-3 border rounded-lg">
                    <div className="flex items-center gap-3">
                      <Badge variant="outline">#{index + 1}</Badge>
                      <div>
                        <p className="font-medium">{code.code}</p>
                        <p className="text-sm text-muted-foreground">
                          {code.discount_type === 'percentage' 
                            ? `${code.discount_value}% off` 
                            : `${code.discount_value / 100} RON off`}
                        </p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="font-medium">{code.used_count} uses</p>
                      <p className="text-sm text-muted-foreground">
                        {code.usage_limit ? `of ${code.usage_limit}` : 'unlimited'}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Brevo Integration Status */}
        <Card>
          <CardHeader>
            <CardTitle>Email Delivery Integration</CardTitle>
            <CardDescription>
              Brevo email delivery status and capabilities
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-center justify-between p-3 border rounded-lg bg-green-50">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                  <span className="font-medium">Brevo Integration</span>
                </div>
                <Badge variant="default">Active</Badge>
              </div>

              <div className="flex items-center justify-between p-3 border rounded-lg bg-blue-50">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-blue-500 rounded-full"></div>
                  <span className="font-medium">Manual Discount Emails</span>
                </div>
                <Badge variant="default">Available</Badge>
              </div>

              <div className="flex items-center justify-between p-3 border rounded-lg bg-purple-50">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-purple-500 rounded-full"></div>
                  <span className="font-medium">Auto-Generation Emails</span>
                </div>
                <Badge variant="default">Available</Badge>
              </div>

              <div className="flex items-center justify-between p-3 border rounded-lg bg-orange-50">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 bg-orange-500 rounded-full"></div>
                  <span className="font-medium">Gift Card Emails</span>
                </div>
                <Badge variant="default">Available</Badge>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Email Delivery Insights */}
      <Card>
        <CardHeader>
          <CardTitle>Email Delivery Insights</CardTitle>
          <CardDescription>
            All discount codes, gift cards, and auto-generated codes are delivered via Brevo
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <p className="text-2xl font-bold text-blue-600">{totalCodes}</p>
              <p className="text-sm text-muted-foreground">Total Codes Available for Email</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-purple-600">{autoGeneratedCodes}</p>
              <p className="text-sm text-muted-foreground">Auto-Generated & Emailed</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-green-600">100%</p>
              <p className="text-sm text-muted-foreground">Brevo Integration Coverage</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default DiscountCodeAnalytics;
