// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehvzhnzqcbzuirovwjsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodnpobnpxY2J6dWlyb3Z3anNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDA1NDAsImV4cCI6MjA2NDE3NjU0MH0.dCDXCQsIY2pmVfGBHnRGqi_dw3yTEfkYrOHKnKDLSqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);